/**
 * sync/types.ts — TypeScript интерфейсы для пайплайна синхронизации.
 *
 * Описывает данные, которыми обмениваются фазы: API → трансформация → мерж → БД.
 */

/** Сырая карточка WB из Content API (v2/get/cards/list) */
export interface WBCard {
  nmID: number;
  imtID?: number;
  imt_id?: number;
  vendorCode?: string;
  title?: string;
  imt_name?: string;
  subjectID?: number;
  subject_id?: number;
  subjectName?: string;
  subject_name?: string;
  brand?: string;
  description?: string;
  colors?: Array<{ name: string }>;
  compositions?: Array<{ name: string }>;
  characteristics?: Array<{
    name?: string;
    id?: number;
    value?: string | string[];
    options?: Array<{ name: string; value: string | string[] }>;
  }>;
  photos?: Array<unknown>;
  media?: { photo_count?: number };
  rating?: number;
  feedbacks?: number;
  createdAt?: string;
  updatedAt?: string;
  [key: string]: unknown;
}

/** Цена из WB search API */
export interface WBPrice {
  price: number;          // originalPrice (basic/100)
  discountedPrice: number; // текущая цена (product/100)
  stock: number | null;
}

/** Элемент списка товаров Ozon (v3/product/list) */
export interface OzonListItem {
  offerId: string;
  productId: number;
  productSku: number;
}

/** Инфо о товаре Ozon (v3/product/info/list) */
export interface OzonInfo {
  offer_id?: string;
  name?: string;
  price?: number | string;
  old_price?: number | string;
  images?: string[];
  color_image?: string | string[];
  category?: string;
  stocks?: { stocks?: Array<{ present: number; reserved: number }> };
  reviews_count?: number;
  sources?: Array<{ sku: number }>;
  [key: string]: unknown;
}

/** Атрибуты Ozon (v4/product/info/attributes) */
export interface OzonAttrs {
  offer_id?: string;
  description?: string;
  attributes?: Array<{
    id: number;
    attribute_name: string;
    value: string | string[];
    values?: Array<{ value: string }>;
  }>;
}

/** Рейтинг Ozon (v1/product/rating-by-sku) */
export interface OzonRating {
  rating: number | null;
}

/** Рейтинг WB из search API */
export interface WBRating {
  rating: number;
  feedbacks: number;
}

/** Существующий товар в БД (ключевые поля для сравнения) */
export interface DBProduct {
  id: string;
  slug: string;
  sku: string | null;
  name: string;
  price: number;
  originalPrice: number;
  wbPrice: number | null;
  wbOriginalPrice: number | null;
  ozonPrice: number | null;
  ozonOriginalPrice: number | null;
  currency: string;
  category: string;
  description: string;
  image: string;
  images: string[];
  ozonImage: string | null;
  ozonImages: string[];
  wbArticle: bigint | null;
  ozonArticle: bigint | null;
  imtId?: bigint | null;
  modelId?: string | null;
  colorName: string | null;
  composition: string | null;
  rating: number | null;
  reviewsCount: number | null;
  salesCount?: number | null;
  inStock: boolean;
  wbStock: number | null;
  ozonStock: number | null;
  photoCount: number;
  characteristics: unknown;
  nameAutoGenerated: boolean | null;
  descAutoGenerated: boolean | null;
  archivedAt: Date | null;
  wbCreatedAt: Date | null;
  wbUpdatedAt: Date | null;
}

/** Поля для создания нового товара в БД */
export interface CreateProductData {
  sku?: string | null;
  name: string;
  price: number;
  originalPrice?: number;
  wbPrice?: number | null;
  wbOriginalPrice?: number | null;
  ozonPrice?: number | null;
  ozonOriginalPrice?: number | null;
  category: string;
  description: string;
  image: string;
  images: string[];
  wbArticle?: number | bigint | null;
  ozonArticle?: number | bigint | null;
  rating?: number | null;
  reviewsCount?: number | null;
  colorName?: string | null;
  composition?: string | null;
  inStock?: boolean;
  photoCount?: number;
  characteristics?: unknown;
  nameAutoGenerated?: boolean;
  descAutoGenerated?: boolean;
  wbCreatedAt?: Date | null;
  wbUpdatedAt?: Date | null;
  archivedAt?: Date | null;
}

/** Поля для обновления товара в БД */
export interface UpdateProductData {
  name?: string;
  price?: number;
  originalPrice?: number;
  wbPrice?: number | null;
  wbOriginalPrice?: number | null;
  ozonPrice?: number | null;
  ozonOriginalPrice?: number | null;
  category?: string;
  description?: string;
  image?: string;
  images?: string[];
  ozonImage?: string | null;
  ozonImages?: string[];
  rating?: number | null;
  reviewsCount?: number | null;
  colorName?: string | null;
  composition?: string | null;
  inStock?: boolean;
  photoCount?: number;
  wbStock?: number | null;
  ozonStock?: number | null;
  characteristics?: unknown;
  nameAutoGenerated?: boolean | null;
  descAutoGenerated?: boolean | null;
  wbCreatedAt?: Date | null;
  wbUpdatedAt?: Date | null;
  archivedAt?: Date | null;
  sku?: string | null;
  ozonArticle?: bigint | number | null;
}

/** Результат mergeProductSources */
export interface MergedProductData {
  wbPrice?: number | null;
  wbOriginalPrice?: number | null;
  ozonPrice?: number | null;
  ozonOriginalPrice?: number | null;
  price?: number;
  originalPrice?: number;
  wbStock?: number | null;
  ozonStock?: number | null;
  photoCount?: number;
  image?: string;
  images?: string[];
  ozonImage?: string | null;
  ozonImages?: string[];
  category?: string;
  composition?: string | null;
  colorName?: string | null;
  rating?: number | null;
  reviewsCount?: number | null;
  name?: string;
  nameAutoGenerated?: boolean;
  description?: string;
  descAutoGenerated?: boolean;
  characteristics?: Array<{
    group_name: string;
    options: Array<{ name: string; value: string }>;
  }>;
}

/** Статистика одного запуска */
export interface SyncStats {
  wbCreated: number;
  wbUpdated: number;
  wbSkipped: number;
  ozonCreated: number;
  ozonUpdated: number;
  ozonSkipped: number;
  archived: number;
  outOfStock: number;
  errors: number;
}

/** Маппинг существующих товаров для быстрого поиска */
export interface ExistingProductsMap {
  byWbArticle: Map<number, DBProduct>;
  byOzonArticle: Map<number, DBProduct>;
  byId: Map<string, DBProduct>;
  bySku: Map<string, DBProduct>;
  all: DBProduct[];
}

/** Флаги запуска */
export interface SyncFlags {
  dry: boolean;
  wbOnly: boolean;
  ozonOnly: boolean;
  fromPhase?: string;
}

/** Названия фаз синхронизации (для --from-phase) */
export const SYNC_PHASES = [
  "wb-cards",
  "wb-prices",
  "wb-process",
  "ozon-list",
  "ozon-info",
  "ozon-attrs",
  "ozon-ratings",
  "ozon-process",
  "wb-models",
  "ozon-models",
  "archive",
] as const;

export type SyncPhase = (typeof SYNC_PHASES)[number];
