/**
 * migrate-names.mjs — миграция имён и слагов товаров после добавления цвета в имя.
 *
 * Что делает:
 * 1. Перегенерирует имена авто-названных товаров (nameAutoGenerated = true)
 *    через реальный generateName (категория + состав + цвет) — результат
 *    совпадает с тем, что выдаст следующий синк.
 * 2. Пересчитывает слаги (цвет уже внутри имени — в слаге не дублируется).
 * 3. Пишет data/slug-redirects.json (старый → новый) для 301 в next.config.ts.
 * 4. Архивирует не-сумки (футболки и т.п.) — archivedAt, исчезают из каталога.
 *
 * Использование:
 *   node scripts/migrations/migrate-names.mjs           # preview (ничего не пишет)
 *   node scripts/migrations/migrate-names.mjs --apply   # применить + записать redirects
 */

import dotenv from "dotenv";
dotenv.config({ path: ".env.local" });
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { buildUrlSlug, isBagProduct } from "../sync-modules/transform.mjs";
import { generateName } from "../name-generator.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REDIRECTS_FILE = path.join(__dirname, "..", "..", "data", "slug-redirects.json");

const prisma = new PrismaClient({
  adapter: new PrismaPg({
    connectionString: process.env.DATABASE_URL || "",
    connectionTimeoutMillis: 20_000,
    query_timeout: 60_000,
  }),
});

/** Уникализация слага среди товаров БД + уже занятых в этом прогоне */
function uniqueSlug(products, base, excludeId, usedInRun) {
  let candidate = base;
  let n = 2;
  for (;;) {
    const conflict = products.some(
      (p) => p.slug === candidate && p.id !== excludeId
    );
    if (!conflict && !usedInRun.has(candidate)) return candidate;
    candidate = `${base}-${n}`;
    n++;
  }
}

async function main() {
  const apply = process.argv.includes("--apply");
  console.log(apply ? "=== ПРИМЕНЕНИЕ ===" : "=== PREVIEW ===");
  console.log("");

  const products = await prisma.product.findMany({
    where: { archivedAt: null },
    select: {
      id: true, slug: true, name: true, colorName: true,
      composition: true, category: true, nameAutoGenerated: true,
    },
    orderBy: { name: "asc" },
  });

  console.log(`Товаров активных: ${products.length}\n`);

  // ─── 1. Не-сумки → архив ───
  const toArchive = products.filter((p) => {
    // isBagProduct смотрит subjectName/title — в БД их нет, поэтому
    // дополнительно проверяем имя/состав по ключевым словам не-сумок.
    const haystack = `${p.name || ""} ${p.composition || ""}`.toLowerCase();
    // "лайкра" в составе — верный признак одежды (футболка и т.п.),
    // в премиальных сумках лайкры не бывает.
    const hasLycra = (p.composition || "").toLowerCase().includes("лайкра");
    return hasLycra || !isBagProduct({ subjectName: haystack, title: haystack });
  });

  if (toArchive.length > 0) {
    console.log(`--- Не-сумки (архив): ${toArchive.length} ---`);
    for (const p of toArchive) {
      console.log(`  [архив] ${p.id}  ${(p.name || "").slice(0, 60)}`);
    }
    console.log("");
  }

  // ─── 2. Имена + слаги ───
  const plans = [];
  const usedInRun = new Set();

  for (const p of products) {
    // Авто-имя: перегенерируем с цветом. wbName = текущее имя (для мини-детекта —
    // "мини" уже есть в имени, если сумка мини).
    if (p.nameAutoGenerated) {
      const newName = generateName({
        category: p.category,
        composition: p.composition || null,
        wbName: p.name || null,
        colorName: p.colorName || null,
      });
      if (newName !== p.name) {
        const base = buildUrlSlug(newName, "");
        if (base) {
          const next = uniqueSlug(products, base, p.id, usedInRun);
          usedInRun.add(next);
          // Имя меняем всегда; слаг — только если изменился
          if (next !== p.slug) {
            plans.push({ id: p.id, old: p.slug, next, name: newName });
          } else {
            plans.push({ id: p.id, old: p.slug, next: null, name: newName });
          }
        }
      }
    }
  }

  plans.sort((a, b) => a.old.localeCompare(b.old));

  if (plans.length === 0 && toArchive.length === 0) {
    console.log("Ничего менять не нужно.");
    return;
  }

  if (plans.length > 0) {
    console.log(`--- Товаров с изменением имени+slug: ${plans.length} ---\n`);
    for (const { old: o, next, name } of plans) {
      console.log(`  ${o.padEnd(40)} → ${(next || "—").padEnd(44)}  ${(name || "").slice(0, 50)}`);
    }
    console.log("");
  }

  if (!apply) {
    console.log(`Для применения: node scripts/migrations/migrate-names.mjs --apply`);
    return;
  }

  // ─── Применяем ───
  for (const p of toArchive) {
    await prisma.product.update({
      where: { id: p.id },
      data: { archivedAt: new Date(), inStock: false },
    });
  }

  for (const { id, next, name } of plans) {
    if (next) {
      await prisma.product.update({ where: { id }, data: { slug: next, name } });
    } else {
      await prisma.product.update({ where: { id }, data: { name } });
    }
  }

  // Карта редиректов (301 старые → новые)
  const redirects = {};
  for (const { old: o, next } of plans) {
    if (next) redirects[o] = next;
  }
  fs.writeFileSync(REDIRECTS_FILE, JSON.stringify(redirects, null, 2), "utf8");

  console.log(`Архивировано: ${toArchive.length}`);
  console.log(`Обновлено имён+слагов: ${plans.length}`);
  console.log(`Редиректы записаны: ${REDIRECTS_FILE} (${Object.keys(redirects).length} шт.)`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma["$disconnect"]());