/**
 * Сид-скрипт: заливает data/products.json и data/settings.json в Neon DB.
 * Запуск: npx prisma db seed
 *
 * Делает upsert — если товар уже есть (по id), обновляет; если нет — создаёт.
 */

import { PrismaClient } from "@prisma/client";
import { readFileSync } from "fs";
import { createRequire } from "module";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);

const prisma = new PrismaClient();

/* =============================================
   Типы (локальные, чтобы не тащить всю data/products.ts)
   ============================================= */

/** Минимальный тип для seed'a */
function normalizeProduct(raw) {
  return {
    id: raw.id,
    slug: raw.slug,
    name: raw.name,
    price: raw.price,
    originalPrice: raw.originalPrice || raw.price,
    wbPrice: raw.wbPrice || null,
    wbOriginalPrice: raw.wbOriginalPrice || null,
    ozonPrice: raw.ozonPrice || null,
    ozonOriginalPrice: raw.ozonOriginalPrice || null,
    currency: raw.currency || "₽",
    category: raw.category,
    description: raw.description || "",
    image: raw.image || "",
    images: raw.images || [],
    marketplaces: raw.marketplaces || [],
    wbArticle: raw.wbArticle || null,
    ozonArticle: raw.ozonArticle || null,
    rating: raw.rating || null,
    reviewsCount: raw.reviewsCount || null,
    salesCount: raw.salesCount || null,
    colorName: raw.colorName || null,
    composition: raw.composition || null,
    nameAutoGenerated: raw.nameAutoGenerated ?? null,
    descAutoGenerated: raw.descAutoGenerated ?? null,
    archivedAt: raw.archivedAt ? new Date(raw.archivedAt) : null,
  };
}

/* =============================================
   Seed
   ============================================= */

async function main() {
  console.log("⏳ Seeding database...");

  // ── Products ──
  const productsPath = path.join(__dirname, "..", "data", "products.json");
  const productsFile = JSON.parse(readFileSync(productsPath, "utf-8"));
  const rawProducts = productsFile.products || [];

  console.log(`   Найдено ${rawProducts.length} товаров в products.json`);

  for (const raw of rawProducts) {
    const data = normalizeProduct(raw);
    await prisma.product.upsert({
      where: { id: data.id },
      create: data,
      update: data,
    });
  }
  console.log(`   ✓ Upsert ${rawProducts.length} товаров`);

  // ── Settings ──
  const settingsPath = path.join(__dirname, "..", "data", "settings.json");
  const settingsFile = JSON.parse(readFileSync(settingsPath, "utf-8"));

  await prisma.settings.upsert({
    where: { id: "singleton" },
    create: { id: "singleton", data: settingsFile },
    update: { data: settingsFile },
  });
  console.log("   ✓ Settings сохранены");

  console.log("✅ Seeding complete!");
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
