-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateTable
CREATE TABLE "Model" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "composition" TEXT,
    "dimensions" TEXT,
    "image" TEXT,
    "imtId" BIGINT,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "archivedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Model_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Product" (
    "id" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "sku" TEXT,
    "name" TEXT NOT NULL,
    "price" DOUBLE PRECISION NOT NULL,
    "originalPrice" DOUBLE PRECISION NOT NULL,
    "currency" TEXT NOT NULL DEFAULT '₽',
    "category" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "image" TEXT NOT NULL,
    "images" TEXT[],
    "ozonImage" TEXT,
    "ozonImages" TEXT[],
    "video" TEXT,
    "marketplaces" JSONB NOT NULL DEFAULT '[]',
    "wbArticle" BIGINT,
    "ozonArticle" BIGINT,
    "wbPrice" DOUBLE PRECISION,
    "wbOriginalPrice" DOUBLE PRECISION,
    "ozonPrice" DOUBLE PRECISION,
    "ozonOriginalPrice" DOUBLE PRECISION,
    "ozonRating" DOUBLE PRECISION,
    "ozonReviewsCount" INTEGER,
    "rating" DOUBLE PRECISION,
    "reviewsCount" INTEGER,
    "salesCount" INTEGER,
    "wbStock" INTEGER,
    "ozonStock" INTEGER,
    "colorName" TEXT,
    "composition" TEXT,
    "nameAutoGenerated" BOOLEAN DEFAULT false,
    "descAutoGenerated" BOOLEAN DEFAULT false,
    "archivedAt" TIMESTAMP(3),
    "inStock" BOOLEAN NOT NULL DEFAULT true,
    "characteristics" JSONB,
    "photoCount" INTEGER NOT NULL DEFAULT 1,
    "wbCreatedAt" TIMESTAMP(3),
    "wbUpdatedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "modelId" TEXT,

    CONSTRAINT "Product_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Settings" (
    "id" TEXT NOT NULL DEFAULT 'singleton',
    "data" JSONB NOT NULL,

    CONSTRAINT "Settings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SyncRun" (
    "id" TEXT NOT NULL,
    "platform" TEXT NOT NULL,
    "timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "duration" INTEGER NOT NULL,
    "success" BOOLEAN NOT NULL,
    "error" TEXT,
    "added" INTEGER NOT NULL DEFAULT 0,
    "updated" INTEGER NOT NULL DEFAULT 0,
    "archived" INTEGER NOT NULL DEFAULT 0,
    "skipped" INTEGER NOT NULL DEFAULT 0,
    "errors" INTEGER NOT NULL DEFAULT 0,
    "log" TEXT NOT NULL DEFAULT '',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "SyncRun_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Model_slug_key" ON "Model"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "Model_imtId_key" ON "Model"("imtId");

-- CreateIndex
CREATE UNIQUE INDEX "Product_slug_key" ON "Product"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "Product_sku_key" ON "Product"("sku");

-- CreateIndex
CREATE UNIQUE INDEX "Product_wbArticle_key" ON "Product"("wbArticle");

-- CreateIndex
CREATE UNIQUE INDEX "Product_ozonArticle_key" ON "Product"("ozonArticle");

-- CreateIndex
CREATE INDEX "SyncRun_platform_timestamp_idx" ON "SyncRun"("platform", "timestamp");

-- AddForeignKey
ALTER TABLE "Product" ADD CONSTRAINT "Product_modelId_fkey" FOREIGN KEY ("modelId") REFERENCES "Model"("id") ON DELETE SET NULL ON UPDATE CASCADE;
