/**
 * Интеграционные тесты для mergeProductSources — слияние данных WB/Ozon.
 *
 * Проверяет pipeline: wbPrices + wbRating → mergeProductSources → финальная запись.
 *
 * Использует реальные функции трансформации (transform.mjs, wb-categories, name-generator),
 * что делает тесты настоящей интеграцией, а не unit с моками.
 */

import { describe, it, expect } from "vitest";
import { mergeProductSources } from "../../scripts/sync-modules/merge.mjs";

// ─── Реалистичный wbCard (карточка из WB Content API) ───
function makeWbCard(overrides = {}) {
  return {
    nmID: 123456789,
    vendorCode: "mor-001",
    title: "Сумка женская Balensa",
    imt_name: "Balensa",
    subjectID: 1, // Сумки женские → crossbody
    subjectName: "Сумки женские",
    description: "Элегантная сумка из натуральной кожи. Идеально подходит для повседневного использования.",
    colors: [{ name: "Тауп" }],
    compositions: [{ name: "Натуральная кожа" }],
    media: {
      photo_count: 3,
      photo: [
        {
          big: "https://basket-15.wbbasket.ru/vol1234/part123456/123456789/images/big/1.webp",
          c516x688: "https://basket-15.wbbasket.ru/vol1234/part123456/123456789/images/c516x688/1.webp",
        },
        {
          big: "https://basket-15.wbbasket.ru/vol1234/part123456/123456789/images/big/2.webp",
          c516x688: "https://basket-15.wbbasket.ru/vol1234/part123456/123456789/images/c516x688/2.webp",
        },
        {
          big: "https://basket-15.wbbasket.ru/vol1234/part123456/123456789/images/big/3.webp",
          c516x688: "https://basket-15.wbbasket.ru/vol1234/part123456/123456789/images/c516x688/3.webp",
        },
      ],
    },
    // Плоский формат (старый card.json) — merge.map берёт c.name/c.value напрямую
    characteristics: [
      { name: "Цвет", value: "Тауп" },
      { name: "Состав", value: "Натуральная кожа" },
      { name: "Сезон", value: "Всесезон" },
    ],
    feedbacks: 14,
    ...overrides,
  };
}

// ─── wbPrices (формат search API → mergeProductSources) ───
function makeWbPrices(overrides = {}) {
  return {
    price: 4990,        // оригинал (копейки уже /100 на этапе prices.mjs)
    discountedPrice: 3490,
    stock: 5,
    ...overrides,
  };
}

// ─── wbRating (формат из sync-all.mjs:669 — преобразованный из analytics) ───
function makeWbRating(overrides = {}) {
  return {
    rating: 4.5,
    feedbacks: 14,
    ...overrides,
  };
}

// ─── fake db record ───
function makeDb(overrides = {}) {
  return {
    id: "mor-001",
    name: "Balensa Taup",
    slug: "balensa-taup",
    price: 5000,
    originalPrice: 7000,
    wbPrice: 5000,
    wbOriginalPrice: 7000,
    ozonPrice: null,
    ozonOriginalPrice: null,
    category: "crossbody",
    description: "Old description",
    image: "https://old-cdn.example.com/old.jpg",
    images: ["https://old-cdn.example.com/old.jpg"],
    composition: "Замша",
    colorName: "Бежевый",
    rating: null,
    reviewsCount: null,
    inStock: false,
    wbStock: 0,
    ozonStock: null,
    photoCount: 1,
    characteristics: [],
    nameAutoGenerated: false,
    descAutoGenerated: false,
    wbArticle: null,
    ...overrides,
  };
}

describe("mergeProductSources — интеграция с WB", () => {
  it("обновляет цены из wbPrices", () => {
    const wbCard = makeWbCard();
    const wbPrices = makeWbPrices();
    const wbRating = makeWbRating();
    const db = makeDb();

    const result = mergeProductSources(wbCard, wbPrices, wbRating, null, null, null, db);

    expect(result.wbPrice).toBe(3490);
    expect(result.wbOriginalPrice).toBe(4990);
    expect(result.price).toBe(3490);   // min(wbPrice, ozonPrice)
    expect(result.originalPrice).toBe(4990);
  });

  it("обновляет рейтинг из wbRating (единственный источник звёзд)", () => {
    const wbCard = makeWbCard();
    const wbPrices = makeWbPrices();
    const wbRating = makeWbRating({ rating: 4.2, feedbacks: 10 });
    const db = makeDb({ rating: null, reviewsCount: null });

    const result = mergeProductSources(wbCard, wbPrices, wbRating, null, null, null, db);

    expect(result.rating).toBe(4.2);
    expect(result.reviewsCount).toBe(10);
  });

  it("игнорирует Ozon content rating — не звёздный рейтинг", () => {
    const wbCard = makeWbCard();
    const wbPrices = makeWbPrices();
    const wbRating = makeWbRating({ rating: 4.5, feedbacks: 14 });
    const db = makeDb({ rating: null, reviewsCount: null });

    // ozonRating = content rating (0-100), не звёздный
    const ozonRating = { rating: 95 }; // content quality score
    const ozonInfo = { reviews_count: 7 };

    const result = mergeProductSources(wbCard, wbPrices, wbRating, ozonInfo, null, ozonRating, db);

    // Рейтинг только от WB, Ozon content rating не влияет
    expect(result.rating).toBe(4.5);
    // Количество отзывов суммируется (реальные counts)
    expect(result.reviewsCount).toBe(21); // 14 wb + 7 ozon
  });

  it("обновляет inStock если wbPrices.stock > 0", () => {
    const wbCard = makeWbCard();
    const wbPrices = makeWbPrices({ stock: 5 });
    const db = makeDb({ inStock: false, wbStock: 0, ozonStock: null });

    const result = mergeProductSources(wbCard, wbPrices, null, null, null, null, db);

    expect(result.wbStock).toBe(5);
    expect(result.inStock).toBe(true);
  });

  it("inStock = false если stock 0", () => {
    const wbCard = makeWbCard();
    const wbPrices = makeWbPrices({ stock: 0 });
    const db = makeDb({ inStock: true, wbStock: 5 });

    const result = mergeProductSources(wbCard, wbPrices, null, null, null, null, db);

    expect(result.wbStock).toBe(0);
    expect(result.inStock).toBe(false);
  });

  it("обновляет фото из wbCard (media.photo → geo CDN)", () => {
    const wbCard = makeWbCard();
    const db = makeDb({ image: null, images: [], photoCount: 0 });

    const result = mergeProductSources(wbCard, null, null, null, null, null, db);

    expect(result.photoCount).toBe(3);
    expect(result.image).toContain("kgd-basket-cdn-01bl.geobasket.ru"); // заменён хост
    expect(result.image).toContain("big/1.webp");
    expect(result.images).toHaveLength(3);
    expect(result.images[0]).toContain("kgd-basket-cdn-01bl.geobasket.ru");
    expect(result.images[1]).toContain("big/2.webp");
    expect(result.images[2]).toContain("big/3.webp");
  });

  it("обновляет категорию через resolveCategory (subjectID → crossbody)", () => {
    const wbCard = makeWbCard({ subjectID: 1 });
    const db = makeDb({ category: "tote" });

    const result = mergeProductSources(wbCard, null, null, null, null, null, db);
    expect(result.category).toBe("crossbody");
  });

  it("обновляет состав из wbCard.compositions", () => {
    const wbCard = makeWbCard({ compositions: [{ name: "Натуральная кожа" }] });
    const db = makeDb({ composition: "Замша" });

    const result = mergeProductSources(wbCard, null, null, null, null, null, db);
    expect(result.composition).toBe("Натуральная кожа");
  });

  it("обновляет цвет из wbCard.colors", () => {
    const wbCard = makeWbCard({ colors: [{ name: "Тауп" }] });
    const db = makeDb({ colorName: "Бежевый" });

    const result = mergeProductSources(wbCard, null, null, null, null, null, db);
    expect(result.colorName).toBe("Тауп");
  });

  it("не обновляет название если nameAutoGenerated = false", () => {
    const wbCard = makeWbCard();
    const db = makeDb({ name: "Ручное название", nameAutoGenerated: false });

    const result = mergeProductSources(wbCard, null, null, null, null, null, db);
    expect(result.name).toBeUndefined();
  });

  it("не обновляет описание если descAutoGenerated = false", () => {
    const wbCard = makeWbCard();
    const db = makeDb({ description: "Ручное описание", descAutoGenerated: false });

    const result = mergeProductSources(wbCard, null, null, null, null, null, db);
    expect(result.description).toBeUndefined();
  });

  it("ничего не меняет если все данные совпадают", () => {
    const wbCard = makeWbCard();
    const wbPrices = makeWbPrices();
    const wbRating = makeWbRating();

    // db должен совпадать с тем, что сгенерирует merge из wbCard
    const db = makeDb({
      wbPrice: 3490,
      wbOriginalPrice: 4990,
      price: 3490,
      originalPrice: 4990,
      rating: 4.5,
      reviewsCount: 14,
      inStock: true,
      wbStock: 5,
      composition: "Натуральная кожа",
      colorName: "Тауп",
      category: "crossbody",
      photoCount: 3,
      image: "https://kgd-basket-cdn-01bl.geobasket.ru/vol1234/part123456/123456789/images/big/1.webp",
      images: [
        "https://kgd-basket-cdn-01bl.geobasket.ru/vol1234/part123456/123456789/images/big/1.webp",
        "https://kgd-basket-cdn-01bl.geobasket.ru/vol1234/part123456/123456789/images/big/2.webp",
        "https://kgd-basket-cdn-01bl.geobasket.ru/vol1234/part123456/123456789/images/big/3.webp",
      ],
      characteristics: [
        {
          group_name: "Wildberries",
          options: [
            { name: "Сезон", value: "Всесезон" },
            { name: "Состав", value: "Натуральная кожа" },
            { name: "Цвет", value: "Тауп" },
          ],
        },
      ],
      nameAutoGenerated: false,
      descAutoGenerated: false,
    });

    const result = mergeProductSources(wbCard, wbPrices, wbRating, null, null, null, db);
    expect(Object.keys(result)).toHaveLength(0);
  });

  // ─── Ozon-фаза не перезаписывает категорию товаров с wbArticle ───
  it("Ozon-фаза не меняет category если у товара есть wbArticle", () => {
    const db = makeDb({ wbArticle: 123456789n, category: "crossbody" });
    const ozonInfo = {
      category: "Сумки",
      name: "Сумка-багет Balensa",
      price: 5000,
    };
    const ozonAttrs = {
      attributes: [
        { id: 20259, values: [{ value: "Багет" }] },
      ],
    };
    // wbCard = null → симуляция Ozon-фазы
    const result = mergeProductSources(null, null, null, ozonInfo, ozonAttrs, null, db);
    // Категория НЕ должна измениться — у товара есть wbArticle
    expect(result.category).toBeUndefined();
  });

  it("Ozon-фаза проставляет category если у товара нет wbArticle", () => {
    const db = makeDb({ wbArticle: null, category: "crossbody" });
    const ozonInfo = {
      category: "Сумки",
      name: "Сумка-багет Ozon-Only",
      price: 5000,
    };
    const result = mergeProductSources(null, null, null, ozonInfo, null, null, db);
    // Без wbArticle — Ozon может установить категорию
    expect(result.category).toBe("baguette");
  });

  it("wbCard = null — не падает, возвращает дефолты", () => {
    const result = mergeProductSources(null, null, null, null, null, null, null);
    // merge проставляет fallback-дефолты: category = "crossbody",
    // composition = null, colorName = null (они отличаются от undefined в null-db)
    expect(result).toHaveProperty("category", "crossbody");
    expect(result).toHaveProperty("composition", null);
    expect(result).toHaveProperty("colorName", null);
    expect(Object.keys(result)).toHaveLength(3);
  });
});
