#!/usr/bin/env node
try {
  const { default: dotenv } = await import("dotenv");
  dotenv.config({ path: ".env" });
  dotenv.config({ path: ".env.local" });
} catch {
  // dotenv не установлен (Vercel) — env vars уже в process.env
}
/**
 * sync-all.mjs — Единый скрипт синхронизации Moranti.
 *
 * Использует стабильные официальные API:
 *   Wildberries: Content API + public search API
 *   Ozon:        Seller API (v3 + v4)
 *
 * Использование:
 *   node scripts/sync-all.mjs                        # полный прогон
 *   node scripts/sync-all.mjs --dry                  # пробный
 *   node scripts/sync-all.mjs --wb-only              # только WB
 *   node scripts/sync-all.mjs --ozon-only            # только Ozon
 *   node scripts/sync-all.mjs --from-phase wb-prices # рестарт с фазы
 *
 * Модули:
 *   sync-modules/transform.mjs   — трансформация данных (чистые функции)
 *   sync-modules/merge.mjs       — слияние WB+Ozon данных
 *   sync-modules/models.mjs      — управление моделями и архивация
 */

import { writeFileSync, existsSync, readFileSync, mkdirSync } from "fs";

// --- Imports из модулей ---
import {
  cdnImageUrl,
  cdnImageUrls,
  extractPhotoCount,
  extractDescription,
  resolveCategory,
  makeSlug,
  toBigInt,
  ozonExtractCategory,
  ozonExtractComposition,
  ozonExtractDescription,
  ozonExtractColor,
} from "./sync-modules/transform.mjs";
import { mergeProductSources } from "./sync-modules/merge.mjs";
import { syncModels, syncOzonModels, archiveGoneProducts } from "./sync-modules/models.mjs";

// --- CommonJS зависимости (используем require вместо ESM import,
//     потому что Vercel не резолвит ESM-пакеты в child_process правильно,
//     а require учитывает NODE_PATH) ---
import { createRequire } from "module";
const require = createRequire(import.meta.url);
const { PrismaClient } = require("@prisma/client");
const { PrismaPg } = require("@prisma/adapter-pg");
const { wbToCategory, CATEGORY_RU } = require("./wb-categories.js");
const { generateName } = require("./name-generator.js");

// ============================================================
// Config
// ============================================================

const WB_CONTENT_API = "https://content-api.wildberries.ru";
const WB_ANALYTICS_API = "https://seller-analytics-api.wildberries.ru";
const WB_PRICES_API = "https://discounts-prices-api.wildberries.ru";
const SUPPLIER_ID = Number(process.env.WB_SUPPLIER_ID) || 312222;

const ITEMS_PER_WB_CARDS = 100;
const FETCH_TIMEOUT = 30000;

const flags = {
  dry: process.argv.includes("--dry"),
  wbOnly: process.argv.includes("--wb-only"),
  ozonOnly: process.argv.includes("--ozon-only"),
  fromPhase: null,
};

// Парсим --from-phase <phase>
const fromIdx = process.argv.indexOf("--from-phase");
if (fromIdx !== -1 && fromIdx + 1 < process.argv.length) {
  flags.fromPhase = process.argv[fromIdx + 1];
}

const SKIP_PHASE = flags.fromPhase ? new Set() : null;

// ============================================================
// Фазы синхронизации (для --from-phase)
// ============================================================

const PHASES = [
  "wb-cards",
  "wb-official-prices",
  "wb-stocks",
  "wb-analytics",
  "wb-process",
  "ozon-list",
  "ozon-info",
  "ozon-attrs",
  "ozon-process",
  "wb-models",
  "ozon-models",
  "archive",
];

/**
 * Проверяет, нужно ли выполнять фазу (с учётом --from-phase).
 * @param {string} phase
 * @returns {boolean}
 */
function shouldRun(phase) {
  if (!flags.fromPhase) return true;
  const idx = PHASES.indexOf(phase);
  const fromIdx = PHASES.indexOf(flags.fromPhase);
  if (fromIdx === -1) return true; // неизвестная фаза — выполняем
  return idx >= fromIdx;
}

// ============================================================
// Logger
// ============================================================

const FIELD_LABELS = {
  price: "цена",
  originalPrice: "цена без скидки",
  wbPrice: "цена WB",
  wbOriginalPrice: "цена WB без скидки",
  ozonPrice: "цена Ozon",
  ozonOriginalPrice: "цена Ozon без скидки",
  wbStock: "сток WB",
  ozonStock: "сток Ozon",
  inStock: "наличие",
  rating: "рейтинг",
  reviewsCount: "отзывы",
  salesCount: "продажи",
  image: "главное фото",
  images: "фото",
  photoCount: "количество фото",
  composition: "состав",
  colorName: "цвет",
  name: "название",
  nameAutoGenerated: "название (авто)",
  category: "категория",
  description: "описание",
  descAutoGenerated: "описание (авто)",
  characteristics: "характеристики",
  wbArticle: "артикул WB",
  ozonArticle: "артикул Ozon",
};

function fmtPrice(n) {
  if (n == null) return "—";
  return String(n).replace(/\B(?=(\d{3})+(?!\d))/g, " ") + " ₽";
}

/**
 * Формирует читаемые описания изменений: "цена: 5 000 → 4 500 ₽"
 * @param {object} db — старая запись из БД
 * @param {object} updates — новые значения { field: value }
 * @returns {string[]}
 */
function formatChanges(db, updates) {
  const changes = [];
  for (const [key, newVal] of Object.entries(updates)) {
    const label = FIELD_LABELS[key] || key;
    const oldVal = db?.[key];

    if (typeof newVal === "number" && typeof oldVal === "number") {
      if (key === "price" || key === "originalPrice" || key === "wbPrice" ||
          key === "wbOriginalPrice" || key === "ozonPrice" || key === "ozonOriginalPrice") {
        changes.push(`${label}: ${fmtPrice(oldVal)} → ${fmtPrice(newVal)}`);
      } else {
        changes.push(`${label}: ${oldVal} → ${newVal}`);
      }
    } else if (typeof newVal === "boolean" && typeof oldVal === "boolean") {
      const yesno = (v) => v ? "есть" : "нет";
      if (oldVal !== newVal) changes.push(`${label}: ${yesno(oldVal)} → ${yesno(newVal)}`);
    } else if (key === "images" && Array.isArray(newVal)) {
      changes.push(`${label}: ${oldVal?.length || 0} → ${newVal.length} шт`);
    } else if (typeof newVal === "string") {
      if (newVal.length > 50 || key === "image" || key === "description") {
        changes.push(`${label}: обновлено`);
      } else if (oldVal !== newVal) {
        changes.push(`${label}: «${oldVal || "—"}» → «${newVal}»`);
      }
    } else if (JSON.stringify(newVal) !== JSON.stringify(oldVal)) {
      changes.push(`${label}: обновлено`);
    }
  }
  return changes;
}

const log = {
  lines: [],

  write(msg) {
    process.stdout.write(msg);
    this.lines.push(msg);
  },

  line(msg) {
    console.log(msg);
    this.lines.push(msg + "\n");
  },

  progress(phase, current, total) {
    const msg = JSON.stringify({ type: "progress", phase, current, total });
    console.log(`[PROGRESS] ${msg}`);
    this.lines.push(msg + "\n");
  },

  detail(action, productId, name, changes) {
    const msg = JSON.stringify({ type: "detail", action, product: productId, name, changes });
    console.log(`[DETAIL] ${msg}`);
    this.lines.push(msg + "\n");
  },
};

// ============================================================
// Generic fetch with auth
// ============================================================

async function wbFetch(baseUrl, path, options = {}, attempt = 1) {
  const headers = {
    Authorization: options.apiKey,
    "Content-Type": "application/json",
    ...(options.headers || {}),
  };
  const url = baseUrl + path;
  const resp = await fetch(url, {
    method: options.method || "GET",
    headers,
    body: options.body ? JSON.stringify(options.body) : undefined,
    signal: AbortSignal.timeout(FETCH_TIMEOUT),
  });

  if (resp.status === 429 && attempt <= 3) {
    const retryAfter = parseInt(resp.headers.get("Retry-After") || "1", 10);
    const delay = Math.min(retryAfter * 1000, 30000);
    log.line(`  429 (попытка ${attempt}): повтор через ${delay}мс`);
    await new Promise((r) => setTimeout(r, delay));
    return wbFetch(baseUrl, path, options, attempt + 1);
  }

  if (!resp.ok) {
    const text = await resp.text().catch(() => "");
    throw new Error(`WB API ${resp.status} — ${url}\n${text.slice(0, 300)}`);
  }

  return resp.json();
}



// ============================================================
// Fetch functions
// ============================================================

async function wbFetchAllCards(apiKey, trash = false) {
  const endpoint = trash
    ? "/content/v2/get/cards/trash"
    : "/content/v2/get/cards/list";

  const allCards = [];
  let cursor = { limit: ITEMS_PER_WB_CARDS };
  let total = Infinity;

  log.write(`  Загрузка ${trash ? "удалённых" : "активных"} карточек:`);

  while (allCards.length < total) {
    const body = {
      settings: { cursor, filter: { withPhoto: -1 } },
    };

    const data = await wbFetch(WB_CONTENT_API, endpoint, { method: "POST", apiKey, body });
    const cards = data.cards || [];
    allCards.push(...cards);
    total = data.total || allCards.length;

    log.write(` ${allCards.length}/${total}`);

    if (data.cursor && cards.length === ITEMS_PER_WB_CARDS) {
      cursor = data.cursor;
      await new Promise((r) => setTimeout(r, 200));
    } else {
      break;
    }
  }

  log.line(` — ${allCards.length} карточек`);
  return allCards;
}

import { wbFetchAnalytics } from "./sync-modules/analytics.mjs";
import { wbFetchOfficialPrices } from "./sync-modules/prices.mjs";
import { wbFetchStocks } from "./sync-modules/stocks.mjs";

import {
  ozonFetchAllProducts,
  ozonFetchProductInfo,
  ozonFetchProductAttributes,
} from "./sync-modules/ozon.mjs";

// ============================================================
// DB operations
// ============================================================

async function getExistingProducts(prisma) {
  const all = await prisma.product.findMany({ orderBy: { id: "asc" } });
  return {
    byWbArticle: new Map(all.filter((p) => p.wbArticle).map((p) => [Number(p.wbArticle), p])),
    byOzonArticle: new Map(all.filter((p) => p.ozonArticle).map((p) => [Number(p.ozonArticle), p])),
    byId: new Map(all.map((p) => [p.id, p])),
    bySku: new Map(all.filter((p) => p.sku).map((p) => [p.sku, p])),
    all,
  };
}

async function generateId(prisma) {
  const last = await prisma.product.findFirst({
    orderBy: { id: "desc" },
    select: { id: true },
  });
  const num = last ? parseInt(last.id.replace("mor-", ""), 10) + 1 : 1;
  return "mor-" + String(num).padStart(3, "0");
}

async function createProduct(prisma, data) {
  const id = await generateId(prisma);
  const sku = data.sku || null;
  const slug = sku ? makeSlug(sku) : id;

  await prisma.product.create({
    data: {
      id,
      slug,
      sku,
      name: data.name || "",
      price: data.price || 0,
      originalPrice: data.originalPrice || 0,
      currency: "₽",
      category: data.category || "crossbody",
      description: data.description || "",
      image: data.image || "",
      images: data.images || [],
      wbArticle: toBigInt(data.wbArticle),
      ozonArticle: toBigInt(data.ozonArticle),
      wbPrice: data.wbPrice ?? null,
      wbOriginalPrice: data.wbOriginalPrice ?? null,
      ozonPrice: data.ozonPrice ?? null,
      ozonOriginalPrice: data.ozonOriginalPrice ?? null,
      rating: data.rating ?? null,
      reviewsCount: data.reviewsCount ?? null,
      colorName: data.colorName ?? null,
      composition: data.composition ?? null,
      inStock: data.inStock ?? true,
      photoCount: data.photoCount || 1,
      characteristics: data.characteristics ?? null,
      nameAutoGenerated: data.nameAutoGenerated ?? true,
      descAutoGenerated: data.descAutoGenerated ?? true,
      wbCreatedAt: data.wbCreatedAt ?? null,
      wbUpdatedAt: data.wbUpdatedAt ?? null,
      archivedAt: data.archivedAt ?? null,
    },
  });

  return id;
}

async function updateProduct(prisma, id, data) {
  const updateData = {};
  const fields = [
    "name", "price", "originalPrice", "wbPrice", "wbOriginalPrice",
    "ozonPrice", "ozonOriginalPrice", "category", "description",
    "image", "images", "rating", "reviewsCount", "colorName", "composition",
    "inStock", "photoCount", "wbStock", "ozonStock",
    "ozonImage", "ozonImages", "characteristics",
    "nameAutoGenerated", "descAutoGenerated",
    "wbCreatedAt", "wbUpdatedAt", "archivedAt", "sku", "ozonArticle",
  ];

  for (const f of fields) {
    if (data[f] !== undefined) updateData[f] = data[f];
  }

  if (Object.keys(updateData).length === 0) return false;

  if (!flags.dry) {
    await prisma.product.update({ where: { id }, data: updateData });
  }
  return true;
}

// ============================================================
// Main
// ============================================================

async function main() {
  const startTime = Date.now();
  log.line("=== Синхронизация запущена ===\n");

  if (flags.dry) log.line("  [DRY RUN — без записи в БД]\n");
  if (flags.fromPhase) log.line(`  Продолжение с фазы: ${flags.fromPhase}\n`);

  // ─── Проверка ключей ───
  const wbApiKey = process.env.WB_API_KEY;
  const wbAnalyticsKey = process.env.WB_ANALYTICS_API_KEY;
  const wbPricesKey = process.env.WB_PRICES_API_KEY;
  const ozonClientId = process.env.OZON_CLIENT_ID;
  const ozonApiKey = process.env.OZON_API_KEY;

  if (!wbApiKey && !flags.ozonOnly) {
    console.error("ERROR: WB_API_KEY не задан.");
    console.error("  Локально: добавь WB_API_KEY=... в .env.local");
    console.error("  Vercel:   добавь WB_API_KEY в Settings → Environment Variables");
    process.exit(1);
  }
  if ((!ozonClientId || !ozonApiKey) && !flags.wbOnly) {
    console.error("ERROR: OZON_CLIENT_ID и OZON_API_KEY не заданы.");
    console.error("  Локально: добавь в .env.local");
    console.error("  Vercel:   добавь в Settings → Environment Variables");
    process.exit(1);
  }

  const prisma = new PrismaClient({
    adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL || process.env.POSTGRES_PRISMA_URL || "" }),
  });

  const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

  /** Ретрай на случай если БД временно недоступна */
  async function prismaRetry(fn) {
    for (let attempt = 1; attempt <= 3; attempt++) {
      try {
        return await fn();
      } catch (e) {
        if (attempt < 3) {
          console.log(`  Повтор БД ${attempt}/3 через ${attempt}с...`);
          await sleep(attempt * 1000);
        } else {
          throw e;
        }
      }
    }
  }

  try {
    // ─── Загрузка товаров из БД ───
    log.line("Загрузка товаров из БД...");
    const existing = await prismaRetry(() => getExistingProducts(prisma));
    log.line(`  ${existing.all.length} товаров в БД\n`);

    const stats = {
      wbCreated: 0, wbUpdated: 0, wbSkipped: 0,
      ozonCreated: 0, ozonUpdated: 0, ozonSkipped: 0,
      archived: 0, outOfStock: 0, errors: 0,
    };

    let wbArticles = [];
    let ozonArticles = [];
    let ozonItems = [];
    let trashArticles = [];
    let wbCards = [];
    let wbTrashCards = [];
    let wbPriceMap = new Map();
    let wbStockMap = new Map();
    let wbAnalyticsMap = new Map();
    let infoMap, attrMap;

    // ═══════════════════════════════════════════
    // PHASE 1: Wildberries
    // ═══════════════════════════════════════════

    if (!flags.ozonOnly) {
      if (shouldRun("wb-cards")) {
        log.progress("wb-cards", 0, 1);
        log.line("[1/2] Загрузка карточек WB (активные)...");
        wbCards = await wbFetchAllCards(wbApiKey, false);
        wbArticles = wbCards.map((c) => c.nmID);
        log.line(`  ${wbCards.length} активных карточек\n`);
        log.progress("wb-cards", 1, 1);

        log.progress("wb-trash", 0, 1);
        log.line("[2/2] Загрузка карточек WB (корзина)...");
        wbTrashCards = await wbFetchAllCards(wbApiKey, true);
        trashArticles = wbTrashCards.map((c) => c.nmID);
        log.line(`  ${wbTrashCards.length} карточек в корзине\n`);
        log.progress("wb-trash", 1, 1);
      }

      if (shouldRun("wb-official-prices") && wbPricesKey) {
        log.progress("wb-official-prices", 0, 1);
        log.line("Загрузка цен WB (через SDK)...");
        wbPriceMap = await wbFetchOfficialPrices(wbPricesKey, log);
        log.progress("wb-official-prices", 1, 1);
      } else if (shouldRun("wb-official-prices") && !wbPricesKey) {
        log.line("[SKIP] WB_PRICES_API_KEY не задан — цены не обновляются");
      }

      if (shouldRun("wb-stocks") && wbAnalyticsKey) {
        log.progress("wb-stocks", 0, 1);
        log.line("Загрузка стоков WB (через SDK)...");
        wbStockMap = await wbFetchStocks(wbArticles, wbAnalyticsKey, log);
        // Накладываем стоки на wbPriceMap
        let mergedCount = 0;
        for (const [nmId, stock] of wbStockMap) {
          const existing = wbPriceMap.get(nmId);
          if (existing) {
            wbPriceMap.set(nmId, { ...existing, stock });
            mergedCount++;
          } else {
            wbPriceMap.set(nmId, { price: null, discountedPrice: null, stock });
          }
        }
        if (mergedCount > 0) {
          log.line(`  Стоки наложены на ${mergedCount} товаров`);
        }
        log.progress("wb-stocks", 1, 1);
      } else if (shouldRun("wb-stocks") && !wbAnalyticsKey) {
        log.line("[SKIP] WB_ANALYTICS_API_KEY не задан — стоки не обновляются");
      }

      if (shouldRun("wb-analytics") && wbAnalyticsKey) {
        log.progress("wb-analytics", 0, 1);
        log.line("Загрузка аналитики WB (рейтинг)...");
        wbAnalyticsMap = await wbFetchAnalytics(wbArticles, wbAnalyticsKey, log);
        log.progress("wb-analytics", 1, 1);
      } else if (shouldRun("wb-analytics") && !wbAnalyticsKey) {
        log.line("[SKIP] WB_ANALYTICS_API_KEY не задан — рейтинг и стоки только из Content API");
      }

      if (shouldRun("wb-process")) {
        // Строим индекс vendorCode → nmID
        const wbVendorToNm = new Map();
        for (const card of wbCards) {
          const vc = card.vendorCode?.trim();
          if (vc) wbVendorToNm.set(vc, card.nmID);
        }

        log.line("Обработка карточек WB...");
        log.progress("wb-process", 0, wbCards.length);
        for (let i = 0; i < wbCards.length; i++) {
          const card = wbCards[i];
          const article = card.nmID;
          const vendorCode = (card.vendorCode || "").trim();

          let db = vendorCode ? existing.bySku.get(vendorCode) : null;
          if (!db) db = existing.byWbArticle.get(article);

          const wbPrices = wbPriceMap.get(article) || null;

          // WB rating: аналитика (productRating) приоритетнее Content API (card.rating)
          const analytics = wbAnalyticsMap.get(article) || null;
          const wbRating = analytics?.productRating != null
            ? { rating: analytics.productRating, feedbacks: card.feedbacks ?? 0 }
            : (card.rating != null
              ? { rating: card.rating, feedbacks: card.feedbacks ?? 0 }
              : null);

          if (db) {
            const ensureFields = {};
            if (article && !db.wbArticle) ensureFields.wbArticle = toBigInt(article);

            const updates = mergeProductSources(card, wbPrices, wbRating, null, null, null, db);
            const allUpdates = { ...ensureFields, ...updates };
            if (Object.keys(allUpdates).length > 0) {
              const ok = await updateProduct(prisma, db.id, allUpdates);
              if (ok) {
                stats.wbUpdated++;
                log.detail("updated", db.id, db.name, formatChanges(db, allUpdates));
              }
            } else {
              stats.wbSkipped++;
            }
          } else {
            const updates = mergeProductSources(card, wbPrices, wbRating, null, null, null, null);
            const id = await createProduct(prisma, {
              ...updates,
              sku: vendorCode || null,
              wbArticle: article,
              name: updates.name || generateName({
                category: updates.category || resolveCategory(card),
                wbName: card.title || card.imt_name || null,
              }),
              description: updates.description || extractDescription(card),
              image: updates.image || cdnImageUrl(article, 1),
              images: updates.images || cdnImageUrls(article, extractPhotoCount(card)),
              photoCount: updates.photoCount || extractPhotoCount(card),
              wbCreatedAt: card.createdAt ? new Date(card.createdAt) : null,
              wbUpdatedAt: card.updatedAt ? new Date(card.updatedAt) : null,
            });
            log.line(`  Создан: ${id} (sku=${vendorCode}), артикул WB: ${article}`);
            log.detail("created", id, updates.name || card.title || "", []);
            stats.wbCreated++;
          }

          if ((i + 1) % 10 === 0 || i === wbCards.length - 1) {
            log.progress("wb-process", i + 1, wbCards.length);
          }
        }

        log.line(`  WB: ${stats.wbCreated} создано, ${stats.wbUpdated} обновлено\n`);
      }
    }

    // ═══════════════════════════════════════════
    // PHASE 2: Ozon
    // ═══════════════════════════════════════════

    if (!flags.wbOnly) {
      if (shouldRun("ozon-list")) {
        log.progress("ozon-list", 0, 1);
        log.line("[Ozon] Загрузка списка товаров...");
        ozonItems = await ozonFetchAllProducts(ozonClientId, ozonApiKey, log);
        ozonArticles = ozonItems.map((i) => i.productId).filter((id) => id > 0);
        log.line(`  ${ozonItems.length} товаров Ozon\n`);
        log.progress("ozon-list", 1, 1);
      }

      const offerIdList = ozonItems.map((i) => i.offerId).filter(Boolean);

      // Ozon info + attrs — параллельно
      if (shouldRun("ozon-info") || shouldRun("ozon-attrs")) {
        log.line("[Ozon] Загрузка деталей товаров (параллельно)...");

        const fetches = [];
        if (shouldRun("ozon-info")) {
          log.progress("ozon-info", 0, 1);
          fetches.push(
            ozonFetchProductInfo(ozonClientId, ozonApiKey, offerIdList, log)
              .then((r) => { infoMap = r; log.progress("ozon-info", 1, 1); return r; })
          );
        }
        if (shouldRun("ozon-attrs")) {
          log.progress("ozon-attrs", 0, 1);
          fetches.push(
            ozonFetchProductAttributes(ozonClientId, ozonApiKey, offerIdList, log)
              .then((r) => { attrMap = r; log.progress("ozon-attrs", 1, 1); return r; })
          );
        }
        await Promise.all(fetches);
        log.line("");
      }

      if (shouldRun("ozon-process")) {
        log.line("Обработка товаров Ozon...");

        const ozonLocks = new Map();
        for (const p of existing.all) {
          if (p.ozonArticle) ozonLocks.set(Number(p.ozonArticle), p.id);
        }
        const skippedOzonFixes = [];

        const totalOzonItems = ozonItems.filter((i) => i.offerId || i.productId).length;
        log.progress("ozon-process", 0, totalOzonItems);
        let ozonProcessed = 0;

        for (const { offerId, productId, productSku } of ozonItems) {
          if (!offerId && !productId) continue;
          const info = infoMap?.get(offerId);
          const attrs = attrMap?.get(offerId);

          const publicSku = productSku || info?.sources?.[0]?.sku || 0;

          let db = offerId ? existing.bySku.get(offerId) : null;
          if (!db && publicSku) db = existing.byOzonArticle.get(Number(publicSku));
          if (!db) db = existing.byOzonArticle.get(productId);

          if (!info) continue;

          if (db) {
            const ensureFields = {};
            if (publicSku && (!db.ozonArticle || Number(db.ozonArticle) !== Number(publicSku))) {
              const newVal = Number(publicSku);
              const oldVal = db.ozonArticle ? Number(db.ozonArticle) : 0;

              if (oldVal !== newVal) {
                if (oldVal) ozonLocks.delete(oldVal);

                if (ozonLocks.has(newVal)) {
                  skippedOzonFixes.push({ db, newVal, oldVal });
                } else {
                  ozonLocks.set(newVal, db.id);
                  ensureFields.ozonArticle = toBigInt(newVal);
                }
              }
            }

            const updates = mergeProductSources(null, null, null, info, attrs, null, db);
            const allUpdates = { ...ensureFields, ...updates };
            if (Object.keys(allUpdates).length > 0) {
              const ok = await updateProduct(prisma, db.id, allUpdates);
              if (ok) {
                stats.ozonUpdated++;
                log.detail("updated", db.id, db.name, formatChanges(db, allUpdates));
              }
            } else {
              stats.ozonSkipped++;
            }
          } else {
            const ozonPrice = info.price != null ? Number(info.price) : null;
            const ozonOrigPrice = info.old_price != null ? Number(info.old_price) : null;
            const ozonCat = ozonExtractCategory(info, attrs);
            const ozonComp = ozonExtractComposition(attrs);

            const id = await createProduct(prisma, {
              sku: offerId || null,
              name: info.name || "",
              price: ozonPrice || 0,
              originalPrice: ozonOrigPrice || 0,
              ozonPrice,
              ozonOriginalPrice: ozonOrigPrice,
              category: ozonCat || "crossbody",
              description: ozonExtractDescription(attrs),
              image: info.images?.[0] || "",
              images: info.images || [],
              ozonImage: info.images?.[0] || null,
              ozonImages: info.images || [],
              ozonArticle: publicSku || productId,
              photoCount: info.images?.length || 1,
              colorName: ozonExtractColor(info, attrs),
              composition: ozonComp,
              rating: null,
              inStock: info.stocks?.stocks?.some(
                (s) => (s.present || 0) - (s.reserved || 0) > 0
              ) ?? true,
              nameAutoGenerated: true,
              descAutoGenerated: true,
            });
            log.line(`  Создан (Ozon): ${id} (offer=${offerId}), артикул Ozon: ${publicSku || productId}`);
            log.detail("created", id, info.name || "", []);
            stats.ozonCreated++;
          }

          ozonProcessed++;
          if (ozonProcessed % 10 === 0 || ozonProcessed === totalOzonItems) {
            log.progress("ozon-process", ozonProcessed, totalOzonItems);
          }
        }

        // Второй проход: фиксы ozonArticle
        if (skippedOzonFixes.length > 0) {
          log.line(`  Второй проход: повтор для ${skippedOzonFixes.length} пропущенных ozonArticle...`);
          for (const { db, newVal, oldVal } of skippedOzonFixes) {
            if (ozonLocks.has(newVal)) {
              log.line(`    Всё ещё пропущен ${db.id}: ${newVal} занят ${ozonLocks.get(newVal)}`);
            } else {
              ozonLocks.set(newVal, db.id);
              const ok = await updateProduct(prisma, db.id, { ozonArticle: toBigInt(newVal) });
              if (ok) {
                log.line(`    Исправление ozonArticle для ${db.id}: ${oldVal} → ${newVal} (2-й проход)`);
                stats.ozonUpdated++;
              }
            }
          }
        }

        log.line(`  Ozon: ${stats.ozonUpdated} обновлено\n`);
      }
    }

    // ═══════════════════════════════════════════
    // PHASE 3: Models
    // ═══════════════════════════════════════════

    if (shouldRun("ozon-models") && !flags.wbOnly) {
      log.progress("ozon-models", 0, 1);
      const ozonModelResult = await syncOzonModels(prisma, attrMap || new Map(), log);
      if (ozonModelResult.created > 0 || ozonModelResult.assigned > 0) {
        log.line(`  Модели Ozon: ${ozonModelResult.created} создано, ${ozonModelResult.assigned} привязано`);
      }
      log.progress("ozon-models", 1, 1);
    }

    if (shouldRun("wb-models") && !flags.ozonOnly && wbCards.length > 0) {
      log.progress("wb-models", 0, 1);
      log.line("Синхронизация моделей из WB imtId...");
      const modelResult = await syncModels(prisma, wbCards, resolveCategory, log, flags);
      log.line(`  Модели WB: ${modelResult.created} создано, ${modelResult.assigned} привязано\n`);
      log.progress("wb-models", 1, 1);
    }

    // ═══════════════════════════════════════════
    // PHASE 4: Archive
    // ═══════════════════════════════════════════

    if (shouldRun("archive")) {
      log.progress("archive", 0, 1);
      log.line("Архивация удалённых товаров...");
      const archiveResult = await archiveGoneProducts(
        prisma, existing.all, wbArticles, ozonItems, trashArticles,
        !flags.ozonOnly, !flags.wbOnly, log, flags,
      );
      stats.archived = archiveResult.archived;
      stats.outOfStock = archiveResult.markedOutOfStock;
      log.progress("archive", 1, 1);
    }

    // ═══════════════════════════════════════════
    // Summary
    // ═══════════════════════════════════════════

    log.progress("done", 1, 1);
    const duration = ((Date.now() - startTime) / 1000).toFixed(1);

    log.line("\n=== ИТОГ ===");
    log.line(`  WB создано:              ${stats.wbCreated}`);
    log.line(`  WB обновлено:            ${stats.wbUpdated}`);
    log.line(`  WB пропущено:            ${stats.wbSkipped}`);
    log.line(`  WB аналитика:            ${wbAnalyticsMap.size} товаров`);
    log.line(`  Ozon создано:            ${stats.ozonCreated}`);
    log.line(`  Ozon обновлено:          ${stats.ozonUpdated}`);
    log.line(`  Ozon пропущено:          ${stats.ozonSkipped}`);
    log.line(`  Архивировано:            ${stats.archived}`);
    log.line(`  Нет в наличии:           ${stats.outOfStock}`);
    log.line(`  Ошибок:                  ${stats.errors}`);
    log.line(`  Длительность:            ${duration}с`);
    log.line(`  Режим:                   ${flags.dry ? "DRY (без записи)" : "live"}`);

    const skipped = stats.wbSkipped + stats.ozonSkipped;
    const summary = {
      created: stats.wbCreated + stats.ozonCreated,
      updated: stats.wbUpdated + stats.ozonUpdated,
      skipped,
      archived: stats.archived,
      outOfStock: stats.outOfStock,
      errors: stats.errors,
      total: stats.wbCreated + stats.ozonCreated + stats.wbUpdated + stats.ozonUpdated + skipped,
      duration: parseFloat(duration),
    };
    console.log(JSON.stringify(summary));

  } catch (err) {
    console.error("\nFATAL:", err);
    process.exit(1);
  } finally {
    await prisma.$disconnect();
  }
}

main();
