/**
 * sync-wb.mjs — синхронизация каталога с Wildberries (Prisma).
 *
 * Запуск:       node scripts/sync-wb.mjs
 * Из кода:      import { runSync } from './scripts/sync-wb.mjs'
 *
 * Пишет напрямую в Supabase (Prisma). JSON-файлы больше не нужны для работы sync.
 *
 * Источники данных (по приоритету):
 *   1. WB Content API (content-api.wildberries.ru) — если есть WB_API_KEY
 *   2. Публичное API card.wb.ru — без ключа, работает из РФ
 *
 * Что делает:
 *   1. Читает артикулы из Prisma Settings или из fallback-файла
 *   2. Фетчит карточки WB (Content API / card.wb.ru)
 *   3. Обновляет цены, фото, характеристики в Prisma
 *   4. Генерирует названия (если nameAutoGenerated !== false)
 *   5. Создаёт новые товары (mor-NNN, slug = wb-{article})
 *   6. Архивирует удалённые из WB
 *   7. Сохраняет отчёт в data/sync-log.json
 */

import { PrismaClient } from "@prisma/client";
import { readFileSync, writeFileSync, existsSync, unlinkSync, statSync } from "fs";
import { createRequire } from "module";
import path from "path";
import { fileURLToPath } from "url";
import { CDN_HOSTS, sleep } from "./wb-utils.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);
const { wbToCategory } = require("./wb-categories");
const { generateName } = require("./name-generator");

const prisma = new PrismaClient();

/* =============================================
   Paths
   ============================================= */

const DATA_DIR = path.join(__dirname, "..", "data");
const SETTINGS_FILE = path.join(DATA_DIR, "settings.json");
const SYNC_LOG_FILE = path.join(DATA_DIR, "sync-log.json");
const LOCK_FILE = path.join(DATA_DIR, ".sync-lock");

/* =============================================
   Config
   ============================================= */

const CARD_API = "https://card.wb.ru/cards/v2/detail";
const CONTENT_API = "https://content-api.wildberries.ru";
const WB_DOMAIN = "https://www.wildberries.ru";
const BATCH_SIZE = 100;
const FETCH_TIMEOUT = 20000;

/* =============================================
   Helpers
   ============================================= */

function readJSON(file) {
  try {
    return JSON.parse(readFileSync(file, "utf-8"));
  } catch {
    return null;
  }
}

function writeJSON(file, data) {
  writeFileSync(file, JSON.stringify(data, null, 2), "utf-8");
}

/** Читает WB_API_KEY из Prisma settings, settings.json или process.env. */
async function getWbApiKey() {
  try {
    const row = await prisma.settings.findUnique({ where: { id: "singleton" } });
    if (row?.data?.wbApiKey) return row.data.wbApiKey;
  } catch { /* fallback */ }

  const settings = readJSON(SETTINGS_FILE);
  if (settings && settings.wbApiKey) return settings.wbApiKey;
  return process.env.WB_API_KEY || null;
}

function nextId(products) {
  const max = products.reduce((m, p) => {
    const n = parseInt(p.id?.replace("mor-", "") || "0", 10);
    return n > m ? n : m;
  }, 0);
  return "mor-" + String(max + 1).padStart(3, "0");
}

/**
 * Пробует разные CDN-хосты для URL изображения WB.
 */
function wbImageUrls(cdnHost, vol, part, nmId, photoIndexOrId, size) {
  size = size || "c516x688";
  const photoId = typeof photoIndexOrId === "number" ? photoIndexOrId : 1;
  const urls = [];
  for (const host of CDN_HOSTS) {
    urls.push(host + "/vol" + vol + "/part" + part + "/" + nmId + "/images/" + size + "/" + photoId + ".webp");
    urls.push(host + "/vol" + vol + "/part" + part + "/" + nmId + "/images/" + size + "/" + photoId + ".jpg");
  }
  return urls;
}

/** Нормализует объект товара для записи в Prisma. */
function normalizeForDb(p) {
  return {
    id: p.id,
    slug: p.slug,
    name: p.name,
    price: p.price,
    originalPrice: p.originalPrice,
    currency: p.currency || "₽",
    category: p.category,
    description: p.description || "",
    image: p.image || "",
    images: p.images || [],
    marketplaces: p.marketplaces || [],
    wbArticle: p.wbArticle ?? null,
    ozonArticle: p.ozonArticle ?? null,
    rating: p.rating ?? null,
    reviewsCount: p.reviewsCount ?? null,
    salesCount: p.salesCount ?? null,
    imtId: p.imtId ?? null,
    colorName: p.colorName ?? null,
    siblingIds: p.siblingIds || [],
    composition: p.composition ?? null,
    nameAutoGenerated: p.nameAutoGenerated ?? null,
    descAutoGenerated: p.descAutoGenerated ?? null,
    archivedAt: p.archivedAt ? (p.archivedAt instanceof Date ? p.archivedAt : new Date(p.archivedAt)) : null,
  };
}

/** Десериализует Prisma-объект в plain object (Date → string). */
function fromPrisma(p) {
  return {
    ...p,
    archivedAt: p.archivedAt ? p.archivedAt.toISOString() : undefined,
    // Prisma возвращает дату, а код ниже работает со строками или undefined
  };
}

/* =============================================
   Fetch: Content API (требует WB_API_KEY)
   ============================================= */

async function fetchViaContentApi(articles) {
  const apiKey = await getWbApiKey();
  if (!apiKey) return null;

  console.log("[sync] Пробую WB Content API...");
  const allCards = [];
  const batchSize = 100;

  for (let i = 0; i < articles.length; i += batchSize) {
    const batch = articles.slice(i, i + batchSize);

    try {
      const res = await fetch(CONTENT_API + "/content/v2/get/cards/list", {
        method: "POST",
        signal: AbortSignal.timeout(FETCH_TIMEOUT),
        headers: {
          Authorization: apiKey,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          settings: {
            cursor: { limit: batchSize },
            filter: { nmIDs: batch },
          },
        }),
      });

      if (res.status === 401) {
        console.warn("[sync] Content API: невалидный ключ");
        return null;
      }

      if (!res.ok) {
        const text = await res.text();
        console.warn("[sync] Content API вернул", res.status, text.slice(0, 200));
        await sleep(2000);
        continue;
      }

      const json = await res.json();
      const cards = json.cards || [];
      allCards.push(...cards);
    } catch (err) {
      console.warn("[sync] Ошибка Content API:", err.message);
      await sleep(2000);
    }

    if (articles.length > batchSize) await sleep(300);
  }

  return allCards.length > 0 ? allCards : null;
}

/* =============================================
   Fetch: card.wb.ru (публичное, без ключа, из РФ)
   ============================================= */

async function fetchViaCardApi(articles) {
  console.log("[sync] Пробую card.wb.ru...");
  const allCards = [];

  for (let i = 0; i < articles.length; i += BATCH_SIZE) {
    const batch = articles.slice(i, i + BATCH_SIZE);
    const url = CARD_API + "?appType=1&curr=rub&lang=ru&dest=-1257786&nm=" + batch.join(",");

    try {
      const res = await fetch(url, {
        signal: AbortSignal.timeout(FETCH_TIMEOUT),
        headers: {
          "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
          Accept: "application/json, text/plain, */*",
        },
      });

      if (res.status === 403) {
        console.warn("[sync] card.wb.ru: 403 Forbidden (geo-block). Нужен сервер в РФ или API-ключ.");
        return { error: "geo-block", cards: [] };
      }

      if (!res.ok) {
        console.warn("[sync] card.wb.ru вернул", res.status, "жду 3s...");
        await sleep(3000);
        continue;
      }

      const json = await res.json();
      const data = json.data || json;
      const products = data.products || [];

      for (const card of products) {
        if (card && card.id) allCards.push(card);
      }
    } catch (err) {
      console.warn("[sync] Ошибка card.wb.ru:", err.message);
      await sleep(2000);
    }

    if (articles.length > BATCH_SIZE) await sleep(500);
  }

  return { error: null, cards: allCards };
}

/* =============================================
   Fetch: общая точка входа
   ============================================= */

async function fetchWbCards(articles) {
  const contentCards = await fetchViaContentApi(articles);
  if (contentCards) {
    console.log("[sync] Данные получены через Content API");
    return { source: "content-api", cards: contentCards };
  }

  const cardResult = await fetchViaCardApi(articles);
  if (cardResult.error === "geo-block") {
    return { source: null, cards: [], geoBlocked: true };
  }
  if (cardResult.cards.length > 0) {
    console.log("[sync] Данные получены через card.wb.ru");
    return { source: "card-api", cards: cardResult.cards };
  }

  return { source: null, cards: [], geoBlocked: false };
}

/* =============================================
   Extract: Content API → унифицированные поля
   ============================================= */

function extractFromContentCard(card) {
  if (!card || !card.nmId) return null;

  const id = Number(card.nmId);
  const imtId = card.imtID || card.imtId || null;
  const name = (card.title || card.name || "").trim();
  const subjectName = card.subjectName || "";

  const sizes = card.sizes || [];
  let price = 0;
  let originalPrice = 0;
  if (sizes.length > 0) {
    const valid = sizes.filter((s) => {
      const p = s.discountedPrice || s.price || 0;
      return p > 0;
    });
    if (valid.length > 0) {
      price = Math.round(valid.reduce((s, sz) => s + (sz.discountedPrice || sz.price || 0), 0) / valid.length);
      originalPrice = Math.round(valid.reduce((s, sz) => s + (sz.price || 0), 0) / valid.length);
    }
  }

  const photos = card.photos || card.media?.photo || [];
  const images = photos
    .map((p) => {
      const url = typeof p === "string" ? p : p.big || p.url || p.c516x688 || "";
      return url || null;
    })
    .filter(Boolean);

  if (images.length === 0) {
    for (const p of photos) {
      if (p.url) images.push(p.url);
      else if (p.big) images.push(p.big);
    }
  }

  const mainImage = images[0] || null;

  const characteristics = card.characteristics || card.options || [];
  let composition = null;
  let colorName = null;
  for (const ch of characteristics) {
    const chName = (ch.name || ch.key || "").toLowerCase();
    const val = ch.value || "";
    if (chName.includes("состав") || chName.includes("материал")) {
      composition = val;
    }
    if (chName.includes("цвет") && !colorName) {
      colorName = val;
    }
  }

  const rating = card.rating || null;
  const feedbacks = card.feedbacks || card.reviewCount || null;

  return {
    id, imtId, name, subjectId: card.subjectID || card.subjectId || null, subjectName,
    colorName, price, originalPrice, composition, images, mainImage,
    rating, feedbacks,
  };
}

/* =============================================
   Extract: card.wb.ru → унифицированные поля
   ============================================= */

function extractFromCardApi(card) {
  if (!card || !card.id) return null;

  const id = Number(card.id);
  const imtId = card.imt_id || card.imtId || null;
  const name = (card.name || "").trim();
  const subjectId = card.subj_id || card.subjectId || null;
  const subjectName = card.subj_name || card.subjectName || null;

  const colors = card.colors || [];
  const colorName = colors[0]?.name || null;

  const sizes = card.sizes || [];
  let price = 0;
  let originalPrice = 0;
  if (sizes.length > 0) {
    const valid = sizes.filter((s) => (s.price || 0) > 0);
    if (valid.length > 0) {
      price = Math.round(valid.reduce((s, sz) => s + (sz.discountedPrice || sz.price || 0), 0) / valid.length);
      originalPrice = Math.round(valid.reduce((s, sz) => s + (sz.price || 0), 0) / valid.length);
    }
  }

  const options = card.options || card.characteristics || [];
  let composition = null;
  for (const opt of options) {
    const optName = (opt.name || "").toLowerCase();
    const val = opt.value || "";
    if (optName.includes("состав") || optName.includes("материал")) {
      composition = val;
    }
    if (!composition && optName === "composition") {
      composition = val;
    }
  }

  const media = card.media || {};
  const photos = media.photo || media.images || [];
  const images = [];
  const vol = card.volume || card.vol || null;
  const part = card.part || null;

  if (vol && part) {
    for (let i = 0; i < Math.min(photos.length, 50); i++) {
      const imgId = photos[i];
      const photoId = typeof imgId === "number" ? imgId : i + 1;
      const cdnUrl = CDN_HOSTS[0] + "/vol" + vol + "/part" + part + "/" + id + "/images/c516x688/" + photoId + ".webp";
      images.push(cdnUrl);
    }
  }

  const mainImage = images[0] || null;

  const rating = card.rating || null;
  const feedbacks = card.feedbacks || card.reviewCount || null;

  return {
    id, imtId, name, subjectId, subjectName, colorName,
    price, originalPrice, composition, images, mainImage,
    rating, feedbacks,
  };
}

/* =============================================
   Загрузка существующих товаров
   ============================================= */

async function loadExistingProducts() {
  try {
    const rows = await prisma.product.findMany({ orderBy: { createdAt: "asc" } });
    if (rows.length > 0) {
      console.log(`[sync] Загружено ${rows.length} товаров из Prisma`);
      return rows.map(fromPrisma);
    }
  } catch (err) {
    console.warn("[sync] Prisma недоступна, читаю JSON:", err.message);
  }
  // Fallback
  const data = readJSON(path.join(DATA_DIR, "products.json"));
  return data?.products || [];
}

/* =============================================
   Загрузка артикулов для синхронизации
   ============================================= */

async function loadArticles(existingProducts) {
  // Пробуем прочитать wbArticles из Prisma Settings
  try {
    const row = await prisma.settings.findUnique({ where: { id: "singleton" } });
    const wbArticles = row?.data?.wbArticles;
    if (Array.isArray(wbArticles) && wbArticles.length > 0) {
      return wbArticles.map(Number).filter(Boolean);
    }
  } catch { /* fallback */ }

  // Fallback: settings.json
  const settings = readJSON(SETTINGS_FILE);
  if (settings?.wbArticles && Array.isArray(settings.wbArticles) && settings.wbArticles.length > 0) {
    return settings.wbArticles.map(Number).filter(Boolean);
  }

  // Последний fallback: артикулы из существующих товаров
  return existingProducts.map((p) => p.wbArticle).filter(Boolean).map(Number);
}

/* =============================================
   Сохранение результатов в Prisma
   ============================================= */

async function saveProducts(products) {
  const batchSize = 20;
  for (let i = 0; i < products.length; i += batchSize) {
    const batch = products.slice(i, i + batchSize);
    await Promise.all(
      batch.map((p) =>
        prisma.product.upsert({
          where: { id: p.id },
          create: normalizeForDb(p),
          update: normalizeForDb(p),
        }),
      ),
    );
  }
  console.log(`[sync] Prisma: сохранено ${products.length} товаров`);
}

/* =============================================
   Main sync
   ============================================= */

async function runSync() {
  const startTime = Date.now();

  // ── Lock ──
  if (existsSync(LOCK_FILE)) {
    const lockAge = Date.now() - statSync(LOCK_FILE).mtimeMs;
    if (lockAge < 300_000) {
      return { error: "Синхронизация уже запущена" };
    }
    unlinkSync(LOCK_FILE);
  }
  writeFileSync(LOCK_FILE, String(Date.now()), "utf-8");

  try {
    // ── Читаем существующие товары (Prisma → JSON fallback) ──
    const existingProducts = await loadExistingProducts();

    // ── Артикулы для синхронизации ──
    const articles = await loadArticles(existingProducts);

    if (articles.length === 0) {
      return {
        error: "Нет артикулов для синхронизации.\n" +
          "Добавьте артикулы в админке → Настройки → WB Articles\n" +
          "или в settings.json (wbArticles[]).",
      };
    }

    // ── Фетчим карточки WB ──
    console.log("[sync] Загружаю", articles.length, "карточек с WB...");
    const result = await fetchWbCards(articles);

    if (result.geoBlocked && !(await getWbApiKey())) {
      return {
        error:
          "card.wb.ru недоступен (403 — geo-block). Укажите WB_API_KEY в настройках сайта.\n" +
          "1. Зайдите в админку → Настройки → WB API Key\n" +
          "2. Или задайте WB_API_KEY в .env.local\n" +
          "3. Запустите синхронизацию снова",
      };
    }

    if (!result.cards || result.cards.length === 0) {
      return { error: "Не удалось загрузить данные с WB. Проверьте API-ключ или подключение." };
    }

    const cards = result.cards;
    const source = result.source;
    const extractFn = source === "content-api" ? extractFromContentCard : extractFromCardApi;

    console.log("[sync] Загружено карточек:", cards.length);

    // ── Обрабатываем ──
    const updated = [];
    const added = [];
    const archived = [];
    const skipped = [];
    const newProducts = [];
    const processedArticleIds = new Set();

    for (const card of cards) {
      const data = extractFn(card);
      if (!data) continue;

      processedArticleIds.add(data.id);

      const existing = existingProducts.find((p) => p.wbArticle === data.id);

      if (existing) {
        const changes = [];

        if (data.price > 0 && data.price !== existing.price) {
          existing.price = data.price;
          changes.push("price");
        }
        if (data.originalPrice > 0 && data.originalPrice !== existing.originalPrice) {
          existing.originalPrice = data.originalPrice;
          changes.push("originalPrice");
        }
        if (data.images.length > 0) {
          existing.images = data.images;
          existing.image = data.mainImage || data.images[0];
          changes.push("images");
        }
        if (data.imtId && data.imtId !== existing.imtId) {
          existing.imtId = data.imtId;
          changes.push("imtId");
        }
        if (data.colorName && data.colorName !== existing.colorName) {
          existing.colorName = data.colorName;
          changes.push("colorName");
        }
        if (data.composition && data.composition !== existing.composition) {
          existing.composition = data.composition;
          changes.push("composition");
        }
        if (data.rating !== undefined && data.rating !== null) {
          if (existing.rating !== data.rating) {
            existing.rating = data.rating;
            changes.push("rating");
          }
        }
        if (data.feedbacks !== undefined && data.feedbacks !== null) {
          if (existing.reviewsCount !== data.feedbacks) {
            existing.reviewsCount = data.feedbacks;
            changes.push("reviewsCount");
          }
        }

        // Название — только если авто-генерированное
        if (existing.nameAutoGenerated !== false) {
          const generated = generateName({
            category: existing.category,
            composition: existing.composition,
            wbName: data.name,
          });
          if (generated !== existing.name) {
            existing.name = generated;
            changes.push("name");
          }
          existing.nameAutoGenerated = true;
        }

        // Ссылки на маркетплейсы
        if (data.id && !existing.marketplaces?.some((m) => m.name === "Wildberries")) {
          if (!existing.marketplaces) existing.marketplaces = [];
          existing.marketplaces.push({
            name: "Wildberries",
            url: WB_DOMAIN + "/catalog/" + data.id + "/detail.aspx",
            icon: "/images/icons/wb.svg",
          });
          changes.push("marketplaces");
        }

        newProducts.push(existing);

        if (changes.length > 0) {
          updated.push({ id: existing.id, name: existing.name, changes });
        } else {
          skipped.push({ id: existing.id, name: existing.name });
        }
      } else {
        // Новый товар
        const category = wbToCategory(data.subjectId, data.subjectName);
        const name = generateName({ category, composition: data.composition, wbName: data.name });
        const newId = nextId(existingProducts.concat(newProducts));

        const product = {
          id: newId,
          slug: "product-mor-" + newId.replace("mor-", ""),
          name,
          price: data.price,
          originalPrice: data.originalPrice || data.price,
          currency: "₽",
          category,
          description: data.name || "",
          image: data.mainImage || "",
          images: data.images || [],
          marketplaces: [{
            name: "Wildberries",
            url: WB_DOMAIN + "/catalog/" + data.id + "/detail.aspx",
            icon: "/images/icons/wb.svg",
          }],
          wbArticle: data.id,
          imtId: data.imtId || null,
          colorName: data.colorName || null,
          composition: data.composition || null,
          rating: data.rating || null,
          reviewsCount: data.feedbacks || null,
          nameAutoGenerated: true,
          descAutoGenerated: true,
          siblingIds: [data.id],
        };

        newProducts.push(product);
        added.push({ id: newId, name });
      }
    }

    // ── Архивируем товары, которых нет в WB ──
    for (const existing of existingProducts) {
      if (existing.wbArticle && !processedArticleIds.has(existing.wbArticle)) {
        existing.archivedAt = new Date().toISOString();
        existing.wbArticle = null;
        archived.push({ id: existing.id, name: existing.name });
        newProducts.push(existing);
      } else if (existing.wbArticle && processedArticleIds.has(existing.wbArticle)) {
        if (existing.archivedAt) {
          delete existing.archivedAt;
        }
        if (!newProducts.includes(existing)) {
          newProducts.push(existing);
        }
      } else if (!existing.wbArticle) {
        if (!newProducts.includes(existing)) {
          newProducts.push(existing);
        }
      }
    }

    // ── Сохраняем в Prisma ──
    await saveProducts(newProducts);

    // Обновляем также JSON (на случай если админка падает на JSON)
    try {
      const productsPath = path.join(DATA_DIR, "products.json");
      const oldJson = readJSON(productsPath);
      if (oldJson) {
        const cats = oldJson.categories || [];
        const catCounts = {};
        for (const p of newProducts) {
          catCounts[p.category] = (catCounts[p.category] || 0) + 1;
        }
        for (const cat of cats) {
          cat.count = catCounts[cat.slug] || 0;
        }
        const now = new Date().toISOString();
        writeJSON(productsPath, {
          meta: { ...oldJson.meta, count: newProducts.length, lastModified: now, syncedAt: now },
          categories: cats,
          products: newProducts,
        });
      }
    } catch (err) {
      console.warn("[sync] JSON fallback write skipped (read-only fs?):", err.message);
    }

    // ── Лог ──
    const duration = Date.now() - startTime;
    const report = {
      timestamp: new Date().toISOString(),
      duration,
      source,
      added: added.length,
      updated: updated.length,
      archived: archived.length,
      skipped: skipped.length,
      total: newProducts.length,
      details: { added, updated, archived },
    };

    writeJSON(SYNC_LOG_FILE, report);
    console.log("[sync] Готово за", duration, "ms");

    return report;
  } finally {
    try {
      if (existsSync(LOCK_FILE)) unlinkSync(LOCK_FILE);
    } catch {}
    await prisma.$disconnect();
  }
}

/* =============================================
   CLI
   ============================================= */

if (process.argv[1] && (process.argv[1] === fileURLToPath(import.meta.url) || process.argv[1].endsWith("sync-wb.mjs"))) {
  runSync()
    .then((result) => {
      console.log(JSON.stringify(result, null, 2));
      if (result && result.error) process.exit(1);
    })
    .catch((err) => {
      console.error("Sync error:", err);
      process.exit(1);
    });
}

export { runSync };
