/* =============================================
   Moranti — Product Data
   Источник (чтение): Супрабаза (Prisma)
   ============================================= */

import { readFileSync, existsSync } from "fs";
import path from "path";
import type { Product as PrismaProduct } from "@prisma/client";
import prisma, { prismaQuery } from "@/lib/prisma";
import { cacheGet } from "@/lib/data-cache";
import { logger } from "@/lib/logger";
import { selectProductImages } from "@/lib/product-images";
import { readSettings } from "@/lib/settings";
import { MARKETPLACE_URLS } from "@/lib/marketplaces";
import { EXCLUDED_REVIEW_IDS, FEATURED_REVIEW_IDS } from "./curated-reviews";

/** Загрузить JSON fallback при недоступности БД */
function loadJsonFallback<T>(file: string): T | null {
  try {
    const p = path.join(process.cwd(), "data", file);
    if (!existsSync(p)) return null;
    return JSON.parse(readFileSync(p, "utf-8")) as T;
  } catch {
    return null;
  }
}

export interface MarketplaceLink {
  name: "Wildberries" | "Ozon";
  url: string;
  icon: string;
}

export interface Product {
  id: string;
  slug: string;
  sku?: string;
  name: string;
  price: number;
  originalPrice: number;
  wbPrice?: number;
  wbOriginalPrice?: number;
  wbStock?: number;
  ozonPrice?: number;
  ozonOriginalPrice?: number;
  ozonStock?: number;
  currency: string;
  category: string;
  description: string;
  image: string;
  images: string[];
  /** HLS-видео товара (WB Content API). Показывается в галерее/карточке. */
  video?: string;
  marketplaces: MarketplaceLink[];
  wbArticle: number;
  ozonArticle?: number;
  rating?: number;
  reviewsCount?: number;
  salesCount?: number;
  colorName?: string;
  composition?: string;
  nameAutoGenerated?: boolean;
  descAutoGenerated?: boolean;
  archivedAt?: string;
  updatedAt?: string;
  inStock: boolean;
  wbCreatedAt?: string;
  characteristics?: CharacteristicGroup[];
  photoCount: number;
  modelId?: string;
}

export interface CharacteristicOption {
  name: string;
  value: string;
  charc_type?: number;
}

export interface CharacteristicGroup {
  group_name: string;
  options: CharacteristicOption[];
}

export interface ProductCategory {
  slug: string;
  name: string;
  description: string;
  image: string;
  count: number;
}

/** Отзыв с маркетплейса (импорт scripts/import-reviews.mjs) */
export interface Review {
  id: string;
  source: "wb" | "ozon";
  author?: string;
  rating?: number;
  text: string;
  pros?: string;
  cons?: string;
  reviewedAt?: string;
}

const CATEGORY_INFO: Record<string, { name: string; description: string }> = {
  crossbody: { name: "Кросс-боди", description: "Сумки через плечо" },
  "na-plecho": { name: "На плечо", description: "Сумки на плечо" },
  baguette: { name: "Багет", description: "Сумки-багет" },
  tote: { name: "Тоут", description: "Шоперы и тоуты" },
  saddle: { name: "Седло", description: "Сумки-седло" },
  backpack: { name: "Рюкзак", description: "Рюкзаки" },
};

function mapProduct(p: PrismaProduct): Product {
  // Auto-generate marketplace links from articles if missing in DB
  const storedMps = (p.marketplaces ?? []) as { name: string; url: string; icon: string }[];
  const wbArt = p.wbArticle ? Number(p.wbArticle) : null;
  const ozonArt = p.ozonArticle ? Number(p.ozonArticle) : null;

  const marketplaces: MarketplaceLink[] = [];

  // WB marketplace
  if (wbArt && !storedMps.some((m) => m.name === "Wildberries")) {
    marketplaces.push({
      name: "Wildberries",
      url: MARKETPLACE_URLS.wbProduct(wbArt),
      icon: "/images/icons/wb.svg",
    });
  }
  // Ozon marketplace
  if (ozonArt && !storedMps.some((m) => m.name === "Ozon")) {
    marketplaces.push({
      name: "Ozon",
      url: MARKETPLACE_URLS.ozonProduct(ozonArt),
      icon: "/images/icons/ozon.svg",
    });
  }
  // Include any stored marketplaces not already added
  for (const mp of storedMps) {
    if (!marketplaces.some((m) => m.name === mp.name)) {
      marketplaces.push(mp as MarketplaceLink);
    }
  }

  // Приоритет: реальные URL из БД (от WB API). Fallback — генерация из article + photoCount.
  // Если товар не в наличии на WB и есть фото с Ozon — берём Ozon-фото (selectProductImages).
  const photoCount = p.photoCount || p.images?.length || 1;
  const selected = selectProductImages({
    wbStock: p.wbStock,
    wbArticle: p.wbArticle ? Number(p.wbArticle) : null,
    image: p.image,
    images: p.images,
    ozonImage: p.ozonImage,
    ozonImages: p.ozonImages,
    photoCount,
  });
  const image = selected.image;
  const images = selected.images;

  return {
    id: p.id,
    slug: p.slug,
    sku: p.sku ?? undefined,
    name: p.name,
    price: p.price,
    originalPrice: p.originalPrice,
    wbPrice: p.wbPrice ?? undefined,
    wbOriginalPrice: p.wbOriginalPrice ?? undefined,
    wbStock: p.wbStock ?? undefined,
    ozonPrice: p.ozonPrice ?? undefined,
    ozonOriginalPrice: p.ozonOriginalPrice ?? undefined,
    ozonStock: p.ozonStock ?? undefined,
    currency: p.currency,
    category: p.category,
    description: p.description,
    image,
    images,
    video: p.video ?? undefined,
    marketplaces,
    wbArticle: p.wbArticle ? Number(p.wbArticle) : 0,
    ozonArticle: p.ozonArticle ? Number(p.ozonArticle) : undefined,
    rating: p.rating ?? undefined,
    reviewsCount: p.reviewsCount ?? undefined,
    salesCount: p.salesCount ?? undefined,
    colorName: p.colorName ?? undefined,

    composition: p.composition ?? undefined,
    nameAutoGenerated: p.nameAutoGenerated ?? undefined,
    descAutoGenerated: p.descAutoGenerated ?? undefined,
    archivedAt: p.archivedAt?.toISOString() ?? undefined,
    updatedAt: p.updatedAt?.toISOString() ?? undefined,
    inStock: p.inStock,
    wbCreatedAt: p.wbCreatedAt?.toISOString() ?? undefined,
    characteristics: p.characteristics
      ? (p.characteristics as unknown as CharacteristicGroup[])
      : undefined,
    photoCount,
    modelId: p.modelId ?? undefined,
  };
}

export async function getProducts(): Promise<Product[]> {
  return cacheGet("all-products", async () => {
    try {
      const rows = await prismaQuery(() =>
        prisma.product.findMany({
          where: { archivedAt: null, inStock: true },
          orderBy: { createdAt: "asc" },
        }),
      );
      return rows.map(mapProduct);
    } catch (err) {
      logger.warn("DB unavailable, fallback to products.json", {
        error: (err as Error)?.message,
      });
      const fallback = loadJsonFallback<{ products: Product[] }>("products.json");
      if (!fallback?.products) throw err;
      return fallback.products;
    }
    // 60s свежих + SWR-окно 10 мин: мутации продуктов инвалидируют ключ
  }, 60_000, 600_000);
}

/** Все товары, включая нет в наличии (кроме архивных) */
export async function getAllProducts(): Promise<Product[]> {
  return cacheGet("all-products-all", async () => {
    try {
      const rows = await prismaQuery(() =>
        prisma.product.findMany({ orderBy: { createdAt: "asc" } }),
      );
      return rows.filter((p) => !p.archivedAt).map(mapProduct);
    } catch (err) {
      logger.warn("DB unavailable, fallback to products.json (all)", {
        error: (err as Error)?.message,
      });
      const fallback = loadJsonFallback<{ products: Product[] }>("products.json");
      if (!fallback?.products) throw err;
      return fallback.products;
    }
  }, 60_000, 600_000);
}

export async function getProduct(slug: string): Promise<Product | null> {  // ——— Сначала ищем в кеше неархивных продуктов ———
  const all = await getProducts();
  const found = all.find((p) => p.slug === slug);
  if (found) return found;

  // ——— Архивный товар? Прямой запрос к БД + JSON fallback ———
  return cacheGet(`product:${slug}`, async () => {
    try {
      const row = await prismaQuery(() =>
        prisma.product.findUnique({ where: { slug } }),
      );
      if (row) return mapProduct(row);
    } catch {
      // DB недоступна — fallback на JSON
    }
    const fallback = loadJsonFallback<{ products: Product[] }>("products.json");
    return fallback?.products?.find((p) => p.slug === slug) ?? null;
  }, 60_000, 600_000);
}

/**
 * Отзывы товара с маркетплейсов (единоразовый импорт).
 * Нет БД / нет отзывов → [] — страница работает как раньше.
 */
export async function getReviews(productId: string): Promise<Review[]> {
  return cacheGet(`reviews:${productId}`, async () => {
    try {
      const rows = await prismaQuery(() =>
        prisma.review.findMany({
          where: { productId },
          orderBy: [{ reviewedAt: "desc" }, { createdAt: "desc" }],
        }),
      );
      return rows.map((r) => ({
        id: r.id,
        source: r.source as "wb" | "ozon",
        author: r.author ?? undefined,
        rating: r.rating ?? undefined,
        text: r.text,
        pros: r.pros ?? undefined,
        cons: r.cons ?? undefined,
        reviewedAt: r.reviewedAt?.toISOString(),
      }));
    } catch (err) {
      logger.warn("DB unavailable — reviews skipped", { error: (err as Error)?.message });
      return [];
    }
    // Отзывы импортируются вручную — кеш можно держать долго
  }, 300_000, 3_600_000);
}

/** Группа отзывов одного товара для страницы /reviews */
export interface ShowcaseReviewGroup {
  slug: string;
  name: string;
  image: string;
  rating?: number;
  reviewsCount?: number;
  reviews: Review[];
}

/**
 * Отзывы для витрины /reviews: только с текстом и рейтингом ≥4,
 * сгруппированы по товару (как на карточке — негатив остаётся на МП).
 */
export async function getShowcaseReviews(): Promise<ShowcaseReviewGroup[]> {
  return cacheGet("reviews-showcase", async () => {
    try {
      const rows = await prismaQuery(() =>
        prisma.review.findMany({
          where: { text: { not: "" }, rating: { gte: 4 } },
          orderBy: [{ reviewedAt: "desc" }, { createdAt: "desc" }],
          include: {
            product: {
              select: {
                slug: true,
                name: true,
                images: true,
                rating: true,
                reviewsCount: true,
                archivedAt: true,
              },
            },
          },
        }),
      );

      const groups = new Map<string, ShowcaseReviewGroup>();
      for (const r of rows) {
        if (!r.product || r.product.archivedAt) continue;
        if (EXCLUDED_REVIEW_IDS.includes(r.id)) continue; // скрываем негатив с витрины
        const key = r.product.slug;
        let g = groups.get(key);
        if (!g) {
          g = {
            slug: r.product.slug,
            name: r.product.name,
            image: r.product.images[0] ?? "",
            rating: r.product.rating ?? undefined,
            reviewsCount: r.product.reviewsCount ?? undefined,
            reviews: [],
          };
          groups.set(key, g);
        }
        g.reviews.push({
          id: r.id,
          source: r.source as "wb" | "ozon",
          author: r.author ?? undefined,
          rating: r.rating ?? undefined,
          text: r.text,
          pros: r.pros ?? undefined,
          cons: r.cons ?? undefined,
          reviewedAt: r.reviewedAt?.toISOString(),
        });
      }
      // Товары с наибольшим числом отзывов — первыми
      return [...groups.values()].sort((a, b) => b.reviews.length - a.reviews.length);
    } catch (err) {
      logger.warn("DB unavailable — showcase reviews skipped", {
        error: (err as Error)?.message,
      });
      return [];
    }
    // Отзывы импортируются вручную — кеш можно держать долго
  }, 300_000, 3_600_000);
}

/** Общий рейтинг магазина для сниппетов (главная, каталог) */
export interface StoreRatingStats {
  ratingValue: number;
  reviewCount: number;
}

/**
 * Общий рейтинг магазина для сниппетов (главная, каталог).
 * Источник — рейтинги ПРОДАВЦА на WB и Ozon (scripts/fetch-seller-ratings.mjs
 * пишет их в settings.storeRating): взвешенное среднее по числу оценок.
 * Настроек нет → fallback на среднее по витринным товарам.
 */
export async function getStoreRatingStats(): Promise<StoreRatingStats | null> {
  return cacheGet("store-rating", async () => {
    const settings = await readSettings();
    if (settings.storeRating && settings.storeRating.reviewCount > 0) {
      return {
        ratingValue: settings.storeRating.ratingValue,
        reviewCount: settings.storeRating.reviewCount,
      };
    }

    // Fallback: средневзвешенный по товарам в наличии (настройки ещё не заполнены)
    try {
      const rows = await prismaQuery(() =>
        prisma.product.findMany({
          where: {
            archivedAt: null,
            inStock: true,
            rating: { not: null },
            reviewsCount: { gt: 0 },
          },
          select: { rating: true, reviewsCount: true },
        }),
      );
      const reviewCount = rows.reduce((s, p) => s + (p.reviewsCount ?? 0), 0);
      if (reviewCount === 0) return null;
      const ratingValue =
        rows.reduce(
          (s, p) => s + (p.rating ?? 0) * (p.reviewsCount ?? 0),
          0,
        ) / reviewCount;
      // Округление вниз до 0.1 — не завышаем рейтинг в сниппете
      return {
        ratingValue: Math.floor(ratingValue * 10) / 10,
        reviewCount,
      };
    } catch (err) {
      logger.warn("DB unavailable — store rating skipped", {
        error: (err as Error)?.message,
      });
      return null;
    }
    // Рейтинги продавцов обновляются вручную скриптом; товары — синками
  }, 600_000, 3_600_000);
}

/**
 * Средневзвешенный рейтинг по набору товаров (в наличии, с рейтингом и
 * числом оценок) — для сниппетов каталога и категорий. Округление вниз.
 */
export function computeCatalogRating(
  products: Product[],
): StoreRatingStats | null {
  const list = products.filter(
    (p) =>
      !p.archivedAt &&
      p.inStock !== false &&
      p.rating != null &&
      (p.reviewsCount ?? 0) > 0,
  );
  const reviewCount = list.reduce((s, p) => s + (p.reviewsCount ?? 0), 0);
  if (reviewCount === 0) return null;
  const ratingValue =
    list.reduce((s, p) => s + (p.rating ?? 0) * (p.reviewsCount ?? 0), 0) /
    reviewCount;
  return {
    ratingValue: Math.floor(ratingValue * 10) / 10,
    reviewCount,
  };
}

/**
 * «Лучшие отзывы» для витрины /reviews — вручную отобранные позитивные,
 * развёрнутые отзывы (см. FEATURED_REVIEW_IDS в curated-reviews.ts).
 * Возвращаются строго в заданном порядке.
 */
export async function getBestReviews(limit = 12): Promise<Review[]> {
  return cacheGet("best-reviews-curated", async () => {
    try {
      const rows = await prismaQuery(() =>
        prisma.review.findMany({
          where: { id: { in: FEATURED_REVIEW_IDS } },
          include: {
            product: {
              select: { archivedAt: true, slug: true, name: true },
            },
          },
        }),
      );
      const byId = new Map(rows.map((r) => [r.id, r]));
      const best: Review[] = [];
      for (const id of FEATURED_REVIEW_IDS) {
        const r = byId.get(id);
        if (!r || !r.product || r.product.archivedAt) continue;
        best.push({
          id: r.id,
          source: r.source as "wb" | "ozon",
          author: r.author ?? undefined,
          rating: r.rating ?? undefined,
          text: r.text,
          pros: r.pros ?? undefined,
          cons: r.cons ?? undefined,
          reviewedAt: r.reviewedAt?.toISOString(),
        });
        if (best.length >= limit) break;
      }
      return best;
    } catch (err) {
      logger.warn("DB unavailable — best reviews skipped", {
        error: (err as Error)?.message,
      });
      return [];
    }
    // Отзывы импортируются вручную — кеш долгий
  }, 300_000, 3_600_000);
}

export async function getCategories(): Promise<ProductCategory[]> {  return cacheGet("all-categories", async () => {
    try {
      const counts = await prismaQuery(() =>
        prisma.product.groupBy({
          by: ["category"],
          where: { archivedAt: null, inStock: true },
          _count: { id: true },
        }),
      );

      const countMap = new Map(counts.map((c) => [c.category, c._count.id]));

      return Object.entries(CATEGORY_INFO).map(([slug, info]) => ({
        slug,
        name: info.name,
        description: info.description,
        image: `/images/categories/${slug}.jpg`,
        count: countMap.get(slug) ?? 0,
      }));
    } catch (err) {
      logger.warn("DB unavailable, fallback to products.json for categories", {
        error: (err as Error)?.message,
      });
      const fallback = loadJsonFallback<{
        categories: ProductCategory[];
      }>("products.json");
      if (!fallback?.categories) throw err;
      return fallback.categories;
    }
    // Счётчики категорий меняются только на мутациях — 5 мин свежести
  }, 300_000, 600_000);
}
