/* =============================================
   Moranti — Product Data (54 товара, Wildberries)
   Источник: data/products.json (через JsonRepository)
   ============================================= */

import { JsonRepository } from "@/lib/json-repository";

export interface Product {
  id: string;
  slug: string;
  name: string;
  price: number;
  originalPrice: number;
  currency: string;
  category: string;
  description: string;
  image: string;
  images: string[];
  marketplaces: MarketplaceLink[];
  wbArticle: number;
  ozonArticle?: number;
  rating?: number;
  reviewsCount?: number;
  imtId?: number;
  colorName?: string;
  siblingIds?: number[];
  composition?: string;
  /** Флаг: имя сгенерировано скриптом (если false — ручное, не перезаписывать) */
  nameAutoGenerated?: boolean;
  /** Флаг: описание сгенерировано скриптом */
  descAutoGenerated?: boolean;
  /** Дата архивации (если товар скрыт из WB) */
  archivedAt?: string;
}

export interface MarketplaceLink {
  name: "Wildberries" | "Ozon" | "Yandex Market";
  url: string;
  icon: string;
}

export interface ProductCategory {
  slug: string;
  name: string;
  description: string;
  image: string;
  count: number;
}

interface ProductsData {
  products: Product[];
  categories: ProductCategory[];
}

const defaults = (): ProductsData => ({
  products: [],
  categories: [],
});

const repo = new JsonRepository<ProductsData>("products.json", defaults);

/* ——— Repository access ——— */

export function invalidateProductsCache(): void {
  repo.invalidate();
}

function load(): ProductsData {
  return repo.read();
}

/* ——— Query functions ——— */

export function getProducts(): Product[] {
  return load().products;
}

export function getProduct(slug: string): Product | null {
  return load().products.find((p) => p.slug === slug) ?? null;
}

export function getProductsByCategory(category: string): Product[] {
  return load().products.filter((p) => p.category === category);
}

export function getProductsByWbArticle(article: number): Product | null {
  return load().products.find((p) => p.wbArticle === article) ?? null;
}

export function getCategories(): ProductCategory[] {
  return load().categories;
}

export function preloadProducts(): Product[] {
  return load().products;
}
