/* =============================================
   Moranti — Product Data
   Источник (чтение): Супрабаза (Prisma)
   ============================================= */

import type { Product as PrismaProduct } from "@prisma/client";
import prisma, { prismaQuery } from "@/lib/prisma";
import { cacheGet } from "@/lib/data-cache";

export interface MarketplaceLink {
  name: "Wildberries" | "Ozon" | "Yandex Market";
  url: string;
  icon: string;
}

export interface Product {
  id: string;
  slug: string;
  name: string;
  price: number;
  originalPrice: number;
  currency: string;
  category: string;
  description: string;
  image: string;
  images: string[];
  marketplaces: MarketplaceLink[];
  wbArticle: number;
  ozonArticle?: number;
  rating?: number;
  reviewsCount?: number;
  salesCount?: number;
  imtId?: number;
  colorName?: string;
  siblingIds?: number[];
  composition?: string;
  nameAutoGenerated?: boolean;
  descAutoGenerated?: boolean;
  archivedAt?: string;
}

export interface ProductCategory {
  slug: string;
  name: string;
  description: string;
  image: string;
  count: number;
}

const CATEGORY_INFO: Record<string, { name: string; description: string }> = {
  crossbody: { name: "Кросс-боди", description: "Сумки через плечо" },
  "na-plecho": { name: "На плечо", description: "Сумки на плечо" },
  baguette: { name: "Багет", description: "Сумки-багет" },
  tote: { name: "Тоут", description: "Шоперы и тоуты" },
  saddle: { name: "Седло", description: "Сумки-седло" },
  backpack: { name: "Рюкзак", description: "Рюкзаки" },
};

function mapProduct(p: PrismaProduct): Product {
  const marketplaces = (p.marketplaces ?? []) as unknown as MarketplaceLink[];
  return {
    id: p.id,
    slug: p.slug,
    name: p.name,
    price: p.price,
    originalPrice: p.originalPrice,
    currency: p.currency,
    category: p.category,
    description: p.description,
    image: p.image,
    images: p.images,
    marketplaces,
    wbArticle: p.wbArticle ?? 0,
    ozonArticle: p.ozonArticle ?? undefined,
    rating: p.rating ?? undefined,
    reviewsCount: p.reviewsCount ?? undefined,
    salesCount: p.salesCount ?? undefined,
    imtId: p.imtId ?? undefined,
    colorName: p.colorName ?? undefined,
    siblingIds: p.siblingIds,
    composition: p.composition ?? undefined,
    nameAutoGenerated: p.nameAutoGenerated ?? undefined,
    descAutoGenerated: p.descAutoGenerated ?? undefined,
    archivedAt: p.archivedAt?.toISOString() ?? undefined,
  };
}

export async function getProducts(): Promise<Product[]> {
  return cacheGet("all-products", async () => {
    const rows = await prismaQuery(() =>
      prisma.product.findMany({ orderBy: { createdAt: "asc" } }),
    );
    return rows.filter((p) => !p.archivedAt).map(mapProduct);
  });
}

export async function getProduct(slug: string): Promise<Product | null> {
  return cacheGet(`product:${slug}`, async () => {
    const row = await prismaQuery(() =>
      prisma.product.findUnique({ where: { slug } }),
    );
    return row ? mapProduct(row) : null;
  });
}

export async function getProductsByCategory(
  category: string,
): Promise<Product[]> {
  const rows = await prismaQuery(() =>
    prisma.product.findMany({
      where: { category, archivedAt: null },
      orderBy: { createdAt: "asc" },
    }),
  );
  return rows.map(mapProduct);
}

export async function getProductsByWbArticle(
  article: number,
): Promise<Product | null> {
  const row = await prismaQuery(() =>
    prisma.product.findUnique({ where: { wbArticle: article } }),
  );
  return row ? mapProduct(row) : null;
}

export async function getCategories(): Promise<ProductCategory[]> {
  return cacheGet("all-categories", async () => {
    const counts = await prismaQuery(() =>
      prisma.product.groupBy({
        by: ["category"],
        where: { archivedAt: null },
        _count: { id: true },
      }),
    );

    const countMap = new Map(counts.map((c) => [c.category, c._count.id]));

    return Object.entries(CATEGORY_INFO).map(([slug, info]) => ({
      slug,
      name: info.name,
      description: info.description,
      image: `/images/categories/${slug}.jpg`,
      count: countMap.get(slug) ?? 0,
    }));
  });
}

export async function getAllSlugs(): Promise<string[]> {
  const rows = await prismaQuery(() =>
    prisma.product.findMany({
      where: { archivedAt: null },
      select: { slug: true },
    }),
  );
  return rows.map((r) => r.slug);
}
